#pragma once
#include <limits>
#include <tuple>
#include <map>
#include <vector>
#ifdef DINERO_TEST_ORCHARD_ORIGIN
namespace {
// Fixture material is generated by the actual full reconstruction writer in
// separate storage, then retained in the original store before snapshots.
// RestoreCompact never creates or repairs this original undo material.
std::map<uint32_t,ChainDB::PersistedHeaderMetadata> RetainHistoricalUndo(
        CompactStartupFixture& fixture,const std::vector<uint32_t>& heights) {
    const auto require=[](bool ok,const char* file=__builtin_FILE(),int line=__builtin_LINE()){OrchardAdmissionFixture::Require(ok,file,line);};
    const auto root=fixture.f.path/"historical-undo-material";
    require(std::filesystem::create_directories(root/"archives"/"blocks"));
    for(const auto& entry:std::filesystem::directory_iterator(fixture.f.path/"flatfiles"/"blocks")) {
        if(entry.is_regular_file() && entry.path().filename().string().starts_with("blk"))
            require(std::filesystem::copy_file(entry.path(),root/"archives"/"blocks"/entry.path().filename()));
    }
    BlockStorage files;require(files.init(root/"archives")==Status::Ok);
    ChainDB rebuilt;require(rebuilt.init(root/"candidate")==Status::Ok);
    consensus::BlockReindexer::Config config;
    config.mode=consensus::BlockReindexer::Mode::FULL;config.use_assumevalid=false;
    config.shielded_frontier_output_path=root/"frontier.bin";
    config.shielded_nullifier_db_path=root/"nullifiers.db";
    const auto replay=OrchardReindexOwner::Run(fixture.f.db,rebuilt,fixture.f.token,
        files,root/"archives",root/"candidate",config);
    require(replay.ok());
    if(!replay->success)throw std::runtime_error("historical undo material replay: "+replay->error);
    std::map<uint32_t,ChainDB::PersistedHeaderMetadata> result;
    for(const auto height:heights) {
        require(height && height<Params().orchard_activation_height && height<fixture.f.blocks.size());
        const auto hash=fixture.f.blocks[height].GetHash();
        const auto expected=rebuilt.getHeaderMetadata(hash);require(expected.ok());
        require(bool(expected->status_flags&BLOCK_HAVE_UNDO) && expected->undo_size);
        const auto bytes=files.readUndo({expected->undo_file,expected->undo_pos,expected->undo_size});require(bytes.ok());
        const auto stored=fixture.files->writeUndo(hash,*bytes);require(stored.ok());
        require(stored->offset<=std::numeric_limits<uint32_t>::max());
        const auto prior=fixture.f.db.getHeaderMetadata(hash);require(prior.ok());auto updated=*prior;
        updated.status_flags|=BLOCK_HAVE_UNDO;updated.undo_file=stored->file_number;
        updated.undo_pos=uint32_t(stored->offset);updated.undo_size=stored->size;
        require(fixture.f.db.putHeaderMetadata(fixture.f.token,hash,updated)==Status::Ok);
        result.emplace(height,updated);
    }
    rebuilt.close();return result;
}
}
TEST(OrchardCompactHistoricalUndo, OriginalBytesAndLocationsSurviveReopen) {
    using Access=dinero::OrchardCompactStartupTestAccess;
    std::map<uint32_t,ChainDB::PersistedHeaderMetadata> retained;
    CompactStartupFixture fixture([&](CompactStartupFixture& full){
        retained=RetainHistoricalUndo(full,{1});
    });
    const auto rows=fixture.Rows();const auto archives=fixture.ArchiveBytes();
    for(unsigned reopen=0;reopen<2;++reopen) {
        auto result=Access::Restore(fixture.startup_mutex,fixture.reopened,fixture.f.token,*fixture.files,
            fixture.f.path/"flatfiles",fixture.f.path/("historical-handoff-"+std::to_string(reopen)));
        ASSERT_TRUE(result);const auto& undo=Access::Undo(*result);ASSERT_GT(undo.size(),1u);
        ASSERT_TRUE(undo[1]);const auto& loc=*undo[1];const auto& expected=retained.at(1);
        EXPECT_EQ(std::make_tuple(loc.file_number,loc.data_pos,loc.data_size),
            std::make_tuple(expected.undo_file,expected.undo_pos,expected.undo_size));
        for(uint32_t height=0;height<Params().orchard_activation_height;++height)
            if(height!=1)EXPECT_FALSE(undo[height]);
        EXPECT_EQ(Access::Index(*result)[1]->status&BLOCK_HAVE_UNDO,0u);
        EXPECT_EQ(fixture.Rows(),rows);EXPECT_EQ(fixture.ArchiveBytes(),archives);
        result.reset();if(!reopen){fixture.reopened.close();ASSERT_EQ(fixture.reopened.init(fixture.f.path),Status::Ok);}
    }
}
TEST(OrchardCompactHistoricalUndo, AnotherValidUndoRecordRefusesThenExactRetry) {
    using Access=dinero::OrchardCompactStartupTestAccess;
    std::map<uint32_t,ChainDB::PersistedHeaderMetadata> retained;
    CompactStartupFixture fixture([&](CompactStartupFixture& full){
        retained=RetainHistoricalUndo(full,{1,2});
    });const auto hash=fixture.f.blocks[1].GetHash();
    const auto& original=retained.at(1);const auto& other=retained.at(2);auto bad=original;
    const auto a=fixture.files->readUndo({original.undo_file,original.undo_pos,original.undo_size});
    const auto b=fixture.files->readUndo({other.undo_file,other.undo_pos,other.undo_size});
    ASSERT_TRUE(a.ok());ASSERT_TRUE(b.ok());ASSERT_NE(*a,*b);
    bad.undo_file=other.undo_file;bad.undo_pos=other.undo_pos;bad.undo_size=other.undo_size;
    ASSERT_EQ(fixture.reopened.putHeaderMetadata(fixture.f.token,hash,bad),Status::Ok);
    const auto rows=fixture.Rows();const auto archives=fixture.ArchiveBytes();
    EXPECT_THROW((void)Access::Restore(fixture.startup_mutex,fixture.reopened,fixture.f.token,*fixture.files,
        fixture.f.path/"flatfiles",fixture.f.path/"historical-wrong-record"),std::exception);
    EXPECT_EQ(fixture.Rows(),rows);EXPECT_EQ(fixture.ArchiveBytes(),archives);
    ASSERT_EQ(fixture.reopened.putHeaderMetadata(fixture.f.token,hash,original),Status::Ok);
    auto result=Access::Restore(fixture.startup_mutex,fixture.reopened,fixture.f.token,*fixture.files,
        fixture.f.path/"flatfiles",fixture.f.path/"historical-exact-retry");
    ASSERT_TRUE(result);ASSERT_TRUE(Access::Undo(*result)[1]);
    const auto& loc=*Access::Undo(*result)[1];
    EXPECT_EQ(std::make_tuple(loc.file_number,loc.data_pos,loc.data_size),
        std::make_tuple(original.undo_file,original.undo_pos,original.undo_size));
    EXPECT_EQ(fixture.ArchiveBytes(),archives);
}
#endif
