if(NOT DEFINED MAINWINDOW_SOURCE OR NOT DEFINED RPC_SOURCE)
  message(FATAL_ERROR "MAINWINDOW_SOURCE and RPC_SOURCE are required")
endif()
file(READ "${MAINWINDOW_SOURCE}" UI)
file(READ "${RPC_SOURCE}" RPC)
foreach(forbidden "sendpubliccovenant" "withdrawfromvault" "timelock wiring pending" "QString(64, '0')")
  string(FIND "${UI}" "${forbidden}" found)
  if(NOT found EQUAL -1)
    message(FATAL_ERROR "unsafe placeholder contract path remains: ${forbidden}")
  endif()
endforeach()
foreach(required "wallet.covenant.ctvfund" "wallet.covenant.list" "wallet.covenant.inspect" "Recovery contracts are disabled" "Arbitrary scripts are disabled")
  string(FIND "${UI}" "${required}" found)
  if(found EQUAL -1)
    message(FATAL_ERROR "missing production contract UI guard: ${required}")
  endif()
endforeach()
foreach(required "wallet.covenant.ctvfund" "RequireSpendActivation(context, ProfileType::CTV)" "failed to persist CTV recovery descriptor" "funding_value_una")
  string(FIND "${RPC}" "${required}" found)
  if(found EQUAL -1)
    message(FATAL_ERROR "missing descriptor-backed funding requirement: ${required}")
  endif()
endforeach()
message(STATUS "Contract production wiring guards passed")
