# Exercise the real component ordering with small subdirectory probes. This
# runs on Linux CI too, without requiring Qt or an Apple toolchain.
foreach(case IN ITEMS apple_default apple_explicit_off other_platform)
  set(src "${CMAKE_CURRENT_BINARY_DIR}/metal-default-${case}")
  file(MAKE_DIRECTORY "${src}/miner" "${src}/qt")
  set(apple ON)
  set(expected ON)
  set(override "")
  if(case STREQUAL "apple_explicit_off")
    set(expected OFF)
    set(override "set(MINER_ENABLE_METAL OFF CACHE BOOL \"Explicit opt-out\")")
  elseif(case STREQUAL "other_platform")
    set(apple OFF)
    set(expected OFF)
  endif()
  file(WRITE "${src}/CMakeLists.txt" "cmake_minimum_required(VERSION 3.20)\nproject(MetalDefault NONE)\nset(APPLE ${apple})\nset(DINERO_BUILD_MINER ON CACHE BOOL \"\")\nset(DINERO_BUILD_QT ON CACHE BOOL \"\")\n${override}\ninclude(\"${COMPONENTS_FILE}\")\n")
  file(WRITE "${src}/miner/CMakeLists.txt" "option(MINER_ENABLE_METAL \"Metal backend\" OFF)\nif(NOT MINER_ENABLE_METAL STREQUAL \"${expected}\")\nmessage(FATAL_ERROR \"Wrong Metal option at miner target creation\")\nendif()\nfile(WRITE \"${src}/build/miner-configured\" \"yes\")\n")
  file(WRITE "${src}/qt/CMakeLists.txt" "# Qt configuration follows the miner.\n")
  file(REMOVE_RECURSE "${src}/build")
  execute_process(COMMAND "${CMAKE_COMMAND}" -S "${src}" -B "${src}/build"
                  RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
  if(NOT result EQUAL 0)
    message(FATAL_ERROR "${case}: ${output} ${error}")
  endif()
  if(NOT EXISTS "${src}/build/miner-configured")
    message(FATAL_ERROR "${case}: miner subdirectory was not configured")
  endif()
endforeach()
