#include "dinero/seeder/output.h"

#include <algorithm>
#include <chrono>
#include <ctime>
#include <filesystem>
#include <fstream>
#include <iomanip>
#include <sstream>
#include <system_error>
#include <vector>

namespace dinero {
namespace seeder {

namespace {

std::string format_utc_iso(int64_t unix_ts) {
    std::time_t t = static_cast<std::time_t>(unix_ts);
    std::tm tm{};
#ifdef _WIN32
    gmtime_s(&tm, &t);
#else
    gmtime_r(&t, &tm);
#endif
    std::ostringstream oss;
    oss << std::put_time(&tm, "%Y-%m-%dT%H:%M:%SZ");
    return oss.str();
}

}  // namespace

bool write_seeds_observed(const PeerStore& store,
                          const std::string& output_path,
                          const OutputConfig& cfg) {
    const int64_t now = std::chrono::duration_cast<std::chrono::seconds>(
        std::chrono::system_clock::now().time_since_epoch()).count();
    const int64_t cutoff = now - cfg.healthy_window.count();

    std::vector<PeerStats> snap = store.snapshot();

    std::vector<PeerStats> healthy;
    healthy.reserve(snap.size());
    for (const auto& s : snap) {
        if (s.attempts == 0) continue;
        if (s.last_success_unix < cutoff) continue;
        if (s.success_ratio() < cfg.min_success_ratio) continue;
        healthy.push_back(s);
    }

    // Highest success ratio first, then most-recent success.
    std::sort(healthy.begin(), healthy.end(),
              [](const PeerStats& a, const PeerStats& b) {
                  if (a.success_ratio() != b.success_ratio()) {
                      return a.success_ratio() > b.success_ratio();
                  }
                  return a.last_success_unix > b.last_success_unix;
              });
    if (healthy.size() > cfg.max_entries) healthy.resize(cfg.max_entries);

    const std::string tmp = output_path + ".tmp";
    {
        std::ofstream f(tmp, std::ios::trunc);
        if (!f.is_open()) return false;
        f << "# AUTO-GENERATED by dinero-seeder. Snapshot at "
          << format_utc_iso(now) << " UTC.\n"
          << "# Source-of-truth for fixed seeds remains "
             "contrib/seeds/seeds_main.txt — the maintainer either\n"
          << "# copies entries from this file into seeds_main.txt for the next "
             "release, or\n"
          << "# diffs the two to spot candidates.\n"
          << "#\n"
          << "# Criteria: last successful handshake within "
          << (cfg.healthy_window.count() / 3600) << "h, "
          << "success_ratio >= " << std::fixed << std::setprecision(2)
          << cfg.min_success_ratio << ", capped at "
          << cfg.max_entries << " entries.\n"
          << "#\n";

        for (const auto& s : healthy) {
            std::ostringstream line;
            line << s.ip << ':' << s.port;
            const std::string addr_field = line.str();
            f << addr_field;
            // pad-right to align comments
            const size_t pad = addr_field.size() < 24 ? 24 - addr_field.size() : 1;
            f << std::string(pad, ' ');
            f << "# " << std::fixed << std::setprecision(0)
              << (s.success_ratio() * 100.0) << "% / "
              << s.attempts << " attempts";
            if (!s.last_user_agent.empty()) {
                f << " / " << s.last_user_agent;
            }
            f << '\n';
        }
        f.flush();
    }

    std::error_code ec;
    std::filesystem::rename(tmp, output_path, ec);
    if (ec) {
        std::filesystem::remove(tmp, ec);
        return false;
    }
    return true;
}

}  // namespace seeder
}  // namespace dinero
