#!/usr/bin/env python3
"""Generate include/consensus/chainparamsseeds.h from contrib/seeds/seeds_main.txt.

This is Phase D of v8 peer-discovery work. The header it produces is
compiled into every dinerod / dinero-qt binary as the last-resort
fallback peer list (when peers.dat is empty, DNS seeds fail, and no
-addnode is set, this is the only thing a fresh node can reach).

Run after editing seeds_main.txt:

    python3 contrib/seeds/generate-seeds.py

CMake regenerates the header automatically when seeds_main.txt is newer
than the header (add_custom_command in root CMakeLists.txt). CI runs
this script with `--check` to fail the build if the committed header
drifted from the input.

Format of seeds_main.txt:
  # comment lines start with '#'.
  IP:port   # one entry per line, IPv4 only for now.
"""

import argparse
import ipaddress
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SEEDS_INPUT = ROOT / "contrib" / "seeds" / "seeds_main.txt"
HEADER_OUTPUT = ROOT / "include" / "consensus" / "chainparamsseeds.h"

# IP:port pattern. Strict — we only accept literal IPv4 + numeric port
# for fixed seeds; hostnames belong in vSeeds (DNS-resolved). Port range
# 1-65535 enforced at parse time.
ENTRY_RE = re.compile(r"^(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}):(\d{1,5})$")


def parse_seeds(text: str) -> list[tuple[str, int, str]]:
    """Return list of (ip, port, comment) tuples from seeds_main.txt body."""
    entries: list[tuple[str, int, str]] = []
    for lineno, raw in enumerate(text.splitlines(), start=1):
        # Strip inline comments first (`172.x.y.z:20999  # California`).
        comment = ""
        if "#" in raw:
            data, _, comment = raw.partition("#")
            comment = comment.strip()
        else:
            data = raw

        data = data.strip()
        if not data:
            # Whole line was a comment or blank.
            continue

        m = ENTRY_RE.match(data)
        if not m:
            print(
                f"error: {SEEDS_INPUT.name}:{lineno}: expected IP:port, got "
                f"{data!r}",
                file=sys.stderr,
            )
            sys.exit(2)

        ip_str = m.group(1)
        port = int(m.group(2))

        # Validate IPv4 — ipaddress raises on malformed octets (e.g.
        # 999.0.0.0). Rejects multicast / unspecified / loopback /
        # link-local / private — fixed seeds must be publicly routable.
        try:
            ip = ipaddress.IPv4Address(ip_str)
        except ipaddress.AddressValueError as exc:
            print(
                f"error: {SEEDS_INPUT.name}:{lineno}: invalid IPv4 {ip_str!r}: {exc}",
                file=sys.stderr,
            )
            sys.exit(2)
        if ip.is_loopback or ip.is_private or ip.is_link_local or \
           ip.is_multicast or ip.is_unspecified or ip.is_reserved:
            print(
                f"error: {SEEDS_INPUT.name}:{lineno}: {ip_str} is not publicly "
                "routable (loopback/private/multicast/etc.). Fixed seeds must "
                "be reachable from the public internet.",
                file=sys.stderr,
            )
            sys.exit(2)

        if not 1 <= port <= 65535:
            print(
                f"error: {SEEDS_INPUT.name}:{lineno}: port {port} out of range",
                file=sys.stderr,
            )
            sys.exit(2)

        entries.append((ip_str, port, comment))

    if not entries:
        print(
            f"error: {SEEDS_INPUT.name} has no seed entries — at least one "
            "publicly-routable IP:port required.",
            file=sys.stderr,
        )
        sys.exit(2)

    return entries


def render_header(entries: list[tuple[str, int, str]]) -> str:
    """Build the chainparamsseeds.h string from parsed entries."""
    lines = [
        "// AUTO-GENERATED by contrib/seeds/generate-seeds.py from",
        "// contrib/seeds/seeds_main.txt. Do not edit by hand — re-run the",
        "// generator and commit both files together. CI's --check mode",
        "// will fail the build if this header drifts from the input.",
        "//",
        "// Source of truth: contrib/seeds/seeds_main.txt",
        "// Generator:       contrib/seeds/generate-seeds.py",
        "//",
        "// These addresses are compiled into every dinerod / dinero-qt",
        "// binary as the last-resort fallback peer list. When a fresh",
        "// node boots with no peers.dat and no DNS-seed connectivity,",
        "// this is the entire set of peers it can reach without manual",
        "// -addnode configuration.",
        "",
        "#pragma once",
        "",
        "#include <string>",
        "#include <vector>",
        "",
        "namespace dinero::consensus {",
        "",
        "// Mainnet fixed seed list (Phase D, v8 peer-discovery).",
        "// One entry per pre-release-curated reachable node.",
        f"inline const std::vector<std::string> kFixedSeedsMainnet = {{",
    ]
    for ip, port, comment in entries:
        entry = f'    "{ip}:{port}",'
        if comment:
            entry = f'{entry:<28}  // {comment}'
        lines.append(entry)
    lines += [
        "};",
        "",
        "} // namespace dinero::consensus",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero if the generated header doesn't match the committed one",
    )
    args = parser.parse_args()

    text = SEEDS_INPUT.read_text()
    entries = parse_seeds(text)
    expected = render_header(entries)

    if args.check:
        existing = HEADER_OUTPUT.read_text() if HEADER_OUTPUT.exists() else None
        if existing != expected:
            print(
                f"error: {HEADER_OUTPUT.relative_to(ROOT)} is out of date "
                f"vs {SEEDS_INPUT.relative_to(ROOT)}. Run:\n"
                f"  python3 {Path(__file__).relative_to(ROOT)}",
                file=sys.stderr,
            )
            return 1
        return 0

    HEADER_OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    HEADER_OUTPUT.write_text(expected)
    print(
        f"wrote {HEADER_OUTPUT.relative_to(ROOT)} "
        f"({len(entries)} entries)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
