#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

DINEROD="${DINEROD:-${REPO_ROOT}/build/dinerod}"
DINERO_CLI="${DINERO_CLI:-${REPO_ROOT}/build/dinero-cli}"

SOURCE_DATADIR="${SOURCE_DATADIR:-/Users/haydarevich/src/Blocks_DB}"
RUNTIME_DATADIR="${RUNTIME_DATADIR:-/Users/haydarevich/src/Blocks_DB_runtime}"
RPC_PORT="${RPC_PORT:-20998}"
P2P_PORT="${P2P_PORT:-20999}"
WALLET_SOCKET_PORT="${WALLET_SOCKET_PORT:-50052}"

RUNTIME_CONF="${RUNTIME_DATADIR}/dinero.conf"
CHECKSUM_FILE="${RUNTIME_DATADIR}/blocks.SHA256"
EXPORT_DIR="${EXPORT_DIR:-/Users/haydarevich/src/Blocks_DB_exports_la}"
EXPORT_RPC_SCRIPT="${EXPORT_RPC_SCRIPT:-${REPO_ROOT}/scripts/export_rpc_blocks.py}"
PACK_EXPORTS_SCRIPT="${PACK_EXPORTS_SCRIPT:-${REPO_ROOT}/scripts/pack_exported_blocks.py}"
OFFLINE_REPLAY_SCRIPT="${OFFLINE_REPLAY_SCRIPT:-${REPO_ROOT}/scripts/offline_replay_archive.py}"

usage() {
    cat <<EOF
Usage: $(basename "$0") <prepare|reindex|start|stop|status|probe|inspect-hex|import-hex|import-dir|audit-exports|pack-exports|replay-exports>

Commands:
  prepare   Create a clean archival runtime datadir from ${SOURCE_DATADIR}
  reindex   Rebuild the runtime chainstate from blk*.dat
  start     Start the archival runtime in background mode
  stop      Stop the archival runtime
  status    Print compact RPC status for the archival runtime
  probe     Verify full block-body access at archival heights
  inspect-hex  Decode a trusted exported block hex file locally
  import-hex   Submit one trusted exported block hex file into the archival runtime
  import-dir   Submit sequential block*.hex files from a directory into the archival runtime
  audit-exports Audit a blockNNN.hex export directory and report holes
  pack-exports  Pack blockNNN.hex files into canonical blk*.dat flatfiles
  replay-exports Strictly replay blockNNN.hex files through submitblock on the archival runtime

Environment overrides:
  SOURCE_DATADIR      Source archival material (default: ${SOURCE_DATADIR})
  RUNTIME_DATADIR     Clean runtime datadir (default: ${RUNTIME_DATADIR})
  RPC_PORT            RPC port (default: ${RPC_PORT})
  P2P_PORT            P2P port (default: ${P2P_PORT})
  WALLET_SOCKET_PORT  Wallet socket port (default: ${WALLET_SOCKET_PORT})
  EXPORT_DIR          Exported block hex directory (default: ${EXPORT_DIR})
  DINEROD             dinerod binary path (default: ${DINEROD})
  DINERO_CLI          dinero-cli binary path (default: ${DINERO_CLI})
EOF
}

need_binary() {
    local path="$1"
    local label="$2"
    if [[ ! -x "${path}" ]]; then
        echo "Missing ${label} binary: ${path}" >&2
        exit 1
    fi
}

ensure_runtime_stopped() {
    if pgrep -af "dinerod.*${RUNTIME_DATADIR}" >/dev/null 2>&1; then
        echo "Archival runtime appears to be running for ${RUNTIME_DATADIR}. Stop it first." >&2
        exit 1
    fi
}

write_runtime_config() {
    mkdir -p "${RUNTIME_DATADIR}"
    cat > "${RUNTIME_CONF}" <<EOF
# Local archival runtime generated by scripts/local_archival_node.sh
# Keep this runtime separate from the canonical Mac node at /Users/haydarevich/.dinero
server=1
listen=1
rpcport=${RPC_PORT}
p2pport=${P2P_PORT}
archival=1
EOF
}

prepare_runtime() {
    ensure_runtime_stopped

    if [[ ! -d "${SOURCE_DATADIR}/blocks" ]]; then
        echo "Source block directory missing: ${SOURCE_DATADIR}/blocks" >&2
        exit 1
    fi

    mkdir -p "${RUNTIME_DATADIR}/blocks"
    cp -a "${SOURCE_DATADIR}/blocks/." "${RUNTIME_DATADIR}/blocks/"

    if [[ -d "${SOURCE_DATADIR}/headers" && ! -d "${RUNTIME_DATADIR}/headers" ]]; then
        cp -a "${SOURCE_DATADIR}/headers" "${RUNTIME_DATADIR}/"
    fi

    write_runtime_config

    (
        cd "${RUNTIME_DATADIR}/blocks"
        shasum -a 256 blk*.dat > "${CHECKSUM_FILE}"
    )

    echo "Prepared archival runtime datadir:"
    echo "  source:  ${SOURCE_DATADIR}"
    echo "  runtime: ${RUNTIME_DATADIR}"
    echo "  blocks:  $(du -sh "${RUNTIME_DATADIR}/blocks" | awk '{print $1}')"
    if [[ -d "${RUNTIME_DATADIR}/headers" ]]; then
        echo "  headers: $(du -sh "${RUNTIME_DATADIR}/headers" | awk '{print $1}')"
    fi
    echo "  checksums: ${CHECKSUM_FILE}"
}

run_reindex() {
    need_binary "${DINEROD}" "dinerod"
    ensure_runtime_stopped
    write_runtime_config

    echo "Starting full reindex for ${RUNTIME_DATADIR}"
    "${DINEROD}" \
        --datadir="${RUNTIME_DATADIR}" \
        --rpcport="${RPC_PORT}" \
        --p2pport="${P2P_PORT}" \
        --wallet-socket-port="${WALLET_SOCKET_PORT}" \
        --archival=1 \
        --reindex
}

wait_for_rpc() {
    need_binary "${DINERO_CLI}" "dinero-cli"

    local attempts=90
    local i
    for ((i = 1; i <= attempts; i++)); do
        if "${DINERO_CLI}" -datadir="${RUNTIME_DATADIR}" -rpcport="${RPC_PORT}" getblockchaininfo >/dev/null 2>&1; then
            return 0
        fi
        sleep 1
    done

    echo "RPC did not become ready for ${RUNTIME_DATADIR}" >&2
    return 1
}

block_hex_metadata() {
    local file_path="$1"
    python3 - "${file_path}" <<'PY'
from pathlib import Path
import hashlib
import struct
import sys

path = Path(sys.argv[1])
hexdata = ''.join(path.read_text().split())
raw = bytes.fromhex(hexdata)
if len(raw) < 128:
    raise SystemExit("block hex is shorter than 128-byte header")

header = raw[:128]

def field(name, value):
    print(f"{name}={value}")

field("file", str(path))
field("hex_len", len(hexdata))
field("raw_len", len(raw))
field("version", struct.unpack('<I', header[:4])[0])
field("prev", header[4:36][::-1].hex())
field("merkle", header[36:68][::-1].hex())
field("utreexo", header[68:100][::-1].hex())
field("timestamp", struct.unpack('<Q', header[100:108])[0])
field("bits", struct.unpack('<I', header[108:112])[0])
field("nonce", struct.unpack('<I', header[112:116])[0])
field("reserved_zero", int(header[116:128] == bytes(12)))
field("hash", hashlib.sha256(hashlib.sha256(header).digest()).digest().hex())
PY
}

rpc_chain_info_assignments() {
    local info
    info="$("${DINERO_CLI}" -datadir="${RUNTIME_DATADIR}" -rpcport="${RPC_PORT}" getblockchaininfo)"
    python3 - "${info}" <<'PY'
import json
import sys

info = json.loads(sys.argv[1])
print(f"best_height={info.get('blocks')}")
print(f"best_hash={info.get('bestblockhash')}")
print(f"headers={info.get('headers')}")
print(f"pruned={int(bool(info.get('pruned')))}")
print(f"ibd={int(bool(info.get('initialblockdownload')))}")
PY
}

load_key_value_lines() {
    local target_prefix="$1"
    shift

    local key
    local value
    while IFS='=' read -r key value; do
        if [[ -n "${key}" ]]; then
            printf -v "${target_prefix}_${key}" '%s' "${value}"
        fi
    done < <("$@")
}

start_runtime() {
    need_binary "${DINEROD}" "dinerod"
    ensure_runtime_stopped
    write_runtime_config

    echo "Starting archival runtime in background mode"
    "${DINEROD}" \
        --datadir="${RUNTIME_DATADIR}" \
        --rpcport="${RPC_PORT}" \
        --p2pport="${P2P_PORT}" \
        --wallet-socket-port="${WALLET_SOCKET_PORT}" \
        --archival=1 \
        -daemon

    wait_for_rpc
    print_status
}

stop_runtime() {
    need_binary "${DINERO_CLI}" "dinero-cli"
    "${DINERO_CLI}" -datadir="${RUNTIME_DATADIR}" -rpcport="${RPC_PORT}" stop
}

print_status() {
    need_binary "${DINERO_CLI}" "dinero-cli"

    local info
    info="$("${DINERO_CLI}" -datadir="${RUNTIME_DATADIR}" -rpcport="${RPC_PORT}" getblockchaininfo)"
    python3 -c '
import json
import sys

info = json.load(sys.stdin)
print(f"runtime={sys.argv[1]}")
print(f"rpc_port={sys.argv[2]} p2p_port={sys.argv[3]} wallet_socket_port={sys.argv[4]}")
print(
    "blocks={blocks} headers={headers} pruned={pruned} ibd={ibd}".format(
        blocks=info.get("blocks"),
        headers=info.get("headers"),
        pruned=info.get("pruned"),
        ibd=info.get("initialblockdownload"),
    )
)
print("bestblockhash={}".format(info.get("bestblockhash")))
' "${RUNTIME_DATADIR}" "${RPC_PORT}" "${P2P_PORT}" "${WALLET_SOCKET_PORT}" <<<"${info}"
}

probe_blocks() {
    need_binary "${DINERO_CLI}" "dinero-cli"

    local heights=("$@")
    if [[ ${#heights[@]} -eq 0 ]]; then
        heights=(0 1 100 5000 15000 22000 28000)
    fi

    local height
    for height in "${heights[@]}"; do
        local hash
        hash="$("${DINERO_CLI}" -datadir="${RUNTIME_DATADIR}" -rpcport="${RPC_PORT}" getblockhash "${height}" | tr -d '"\n')"
        local raw
        raw="$("${DINERO_CLI}" -datadir="${RUNTIME_DATADIR}" -rpcport="${RPC_PORT}" getblock "${hash}" 0)"
        local verbose
        verbose="$("${DINERO_CLI}" -datadir="${RUNTIME_DATADIR}" -rpcport="${RPC_PORT}" getblock "${hash}" 1)"
        local raw_hex
        raw_hex="$(python3 -c 'import json,sys; print(json.load(sys.stdin))' <<<"${raw}")"
        local tx_count
        tx_count="$(python3 -c 'import json,sys; print(json.load(sys.stdin).get("nTx"))' <<<"${verbose}")"
        echo "height=${height} hash=${hash} raw_hex_len=${#raw_hex} ntx=${tx_count}"
    done
}

inspect_hex_file() {
    local file_path="${1:-}"
    if [[ -z "${file_path}" ]]; then
        echo "Usage: $(basename "$0") inspect-hex /path/to/blockNNN.hex" >&2
        exit 1
    fi
    if [[ ! -f "${file_path}" ]]; then
        echo "Missing block hex file: ${file_path}" >&2
        exit 1
    fi

    block_hex_metadata "${file_path}"
}

import_hex_file() {
    need_binary "${DINERO_CLI}" "dinero-cli"

    local file_path="${1:-}"
    if [[ -z "${file_path}" ]]; then
        echo "Usage: $(basename "$0") import-hex /path/to/blockNNN.hex" >&2
        exit 1
    fi
    if [[ ! -f "${file_path}" ]]; then
        echo "Missing block hex file: ${file_path}" >&2
        exit 1
    fi

    wait_for_rpc >/dev/null
    load_key_value_lines meta block_hex_metadata "${file_path}"
    load_key_value_lines chain rpc_chain_info_assignments

    if [[ "${meta_reserved_zero:-0}" != "1" ]]; then
        echo "Refusing import: reserved bytes are non-zero in ${file_path}" >&2
        exit 1
    fi

    if "${DINERO_CLI}" -datadir="${RUNTIME_DATADIR}" -rpcport="${RPC_PORT}" getblock "${meta_hash}" 1 >/dev/null 2>&1; then
        local known
        known="$("${DINERO_CLI}" -datadir="${RUNTIME_DATADIR}" -rpcport="${RPC_PORT}" getblock "${meta_hash}" 1)"
        local known_height
        known_height="$(python3 -c 'import json,sys; print(json.load(sys.stdin).get("height"))' <<<"${known}")"
        echo "Already present: ${file_path} height=${known_height} hash=${meta_hash}"
        return 0
    fi

    if [[ "${meta_prev}" != "${chain_best_hash}" && "${ALLOW_FORK_IMPORT:-0}" != "1" ]]; then
        echo "Refusing import: ${file_path} links to prev=${meta_prev} but current tip is ${chain_best_hash} at height ${chain_best_height}" >&2
        echo "Set ALLOW_FORK_IMPORT=1 only if you intentionally want non-tip or fork imports." >&2
        exit 1
    fi

    local block_hex
    block_hex="$(tr -d '[:space:]' < "${file_path}")"
    "${DINERO_CLI}" -datadir="${RUNTIME_DATADIR}" -rpcport="${RPC_PORT}" submitblock "${block_hex}" >/dev/null

    if ! "${DINERO_CLI}" -datadir="${RUNTIME_DATADIR}" -rpcport="${RPC_PORT}" getblock "${meta_hash}" 1 >/dev/null 2>&1; then
        echo "Submission returned success, but block ${meta_hash} is not retrievable after import." >&2
        exit 1
    fi

    local imported
    imported="$("${DINERO_CLI}" -datadir="${RUNTIME_DATADIR}" -rpcport="${RPC_PORT}" getblock "${meta_hash}" 1)"
    local imported_height
    imported_height="$(python3 -c 'import json,sys; print(json.load(sys.stdin).get("height"))' <<<"${imported}")"
    echo "Imported: ${file_path} height=${imported_height} hash=${meta_hash} prev=${meta_prev}"
}

import_hex_dir() {
    local dir_path="${1:-}"
    if [[ -z "${dir_path}" ]]; then
        echo "Usage: $(basename "$0") import-dir /path/to/exported-hex-dir" >&2
        exit 1
    fi
    if [[ ! -d "${dir_path}" ]]; then
        echo "Missing block hex directory: ${dir_path}" >&2
        exit 1
    fi

    local imported_any=0
    local file_path
    while IFS= read -r file_path; do
        imported_any=1
        import_hex_file "${file_path}"
    done < <(find "${dir_path}" -maxdepth 1 -type f -name 'block*.hex' | sort -V)

    if [[ "${imported_any}" -eq 0 ]]; then
        echo "No block*.hex files found in ${dir_path}" >&2
        exit 1
    fi

    print_status
}

audit_exports() {
    python3 "${EXPORT_RPC_SCRIPT}" \
        --out-dir "${1:-${EXPORT_DIR}}" \
        --audit-only
}

pack_exports() {
    local export_dir="${1:-${EXPORT_DIR}}"
    local output_dir="${2:-${RUNTIME_DATADIR}/blocks}"
    python3 "${PACK_EXPORTS_SCRIPT}" \
        --input-dir "${export_dir}" \
        --output-dir "${output_dir}" \
        --network mainnet
}

replay_exports() {
    local export_dir="${1:-${EXPORT_DIR}}"
    python3 "${OFFLINE_REPLAY_SCRIPT}" \
        --archive-dir "${export_dir}" \
        --datadir "${RUNTIME_DATADIR}" \
        --rpc-port "${RPC_PORT}" \
        --require-zero-peers
}

main() {
    local cmd="${1:-}"
    shift || true

    case "${cmd}" in
        prepare)
            prepare_runtime
            ;;
        reindex)
            run_reindex
            ;;
        start)
            start_runtime
            ;;
        stop)
            stop_runtime
            ;;
        status)
            print_status
            ;;
        probe)
            probe_blocks "$@"
            ;;
        inspect-hex)
            inspect_hex_file "$@"
            ;;
        import-hex)
            import_hex_file "$@"
            ;;
        import-dir)
            import_hex_dir "$@"
            ;;
        audit-exports)
            audit_exports "$@"
            ;;
        pack-exports)
            pack_exports "$@"
            ;;
        replay-exports)
            replay_exports "$@"
            ;;
        *)
            usage
            exit 1
            ;;
    esac
}

main "$@"
