#!/bin/bash
# Xcode Project Configuration Helper
# This script prints the exact settings needed for Xcode

echo "📋 Xcode Configuration Instructions"
echo "===================================="
echo ""
echo "⚠️  You must manually configure these in Xcode:"
echo ""
echo "1️⃣  Build Settings → Other Linker Flags"
echo "   Add these flags (one per line):"
echo ""
echo "   -force_load \$(SRCROOT)/Dinero/Dinero/FFI/libdinero_wallet_ffi.a"
echo "   -force_load \$(SRCROOT)/Dinero/Dinero/FFI/libjsoncpp.a"
echo "   -lc++"
echo "   -lz"
echo "   -lsqlite3"
echo "   -ObjC"
echo ""
echo "2️⃣  Build Phases → Link Binary With Libraries"
echo "   Add these libraries (Add Other... → Navigate to FFI folder):"
echo ""
echo "   • libdinero_wallet_ffi.a (set to 'Do Not Embed')"
echo "   • libjsoncpp.a (set to 'Do Not Embed')"
echo "   • libdinero_wallet.a (set to 'Do Not Embed')"
echo "   • libdinero_crypto.a (set to 'Do Not Embed')"
echo ""
echo "3️⃣  Build Settings → Library Search Paths"
echo "   Add this path:"
echo ""
echo "   \$(SRCROOT)/Dinero/Dinero/FFI"
echo ""
echo "4️⃣  Build Settings → Header Search Paths"
echo "   Add this path:"
echo ""
echo "   \$(SRCROOT)/Dinero/Dinero/FFI"
echo ""
echo "===================================="
echo ""
echo "✅ After configuration:"
echo "   1. Clean Build Folder (⌘⇧K)"
echo "   2. Build (⌘B)"
echo ""

