#!/bin/bash
# sweep_fakery.sh - Technical debt analysis script for DineroCoin
# Usage: ./scripts/sweep_fakery.sh [directory] [--fail-on none|critical|any] [--format text|md]

set -euo pipefail

# Default values
TARGET_DIR="${1:-.}"
FAIL_ON="critical"
FORMAT="text"

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --fail-on)
            FAIL_ON="$2"
            shift 2
            ;;
        --format)
            FORMAT="$2"
            shift 2
            ;;
        *)
            if [[ "$1" != "." && "$1" != /* ]]; then
                TARGET_DIR="$1"
            fi
            shift
            ;;
    esac
done

# Colors for text output
RED='\033[0;31m'
YELLOW='\033[1;33m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Find critical patterns (assert(0), abort, etc)
find_criticals() {
    rg -n --hidden --no-ignore -S \
       -g '!**/{.git,build,third_party,vendor,node_modules,_deps}/**' \
       -e '\b(assert\s*\(\s*0\s*\)|abort\s*\(|__builtin_unreachable|UNREACHABLE)\b' \
       "$TARGET_DIR" 2>/dev/null || true
}

# Find TODO/FIXME patterns
find_todos() {
    rg -n --hidden --no-ignore -S \
       -g '!**/{.git,build,third_party,vendor,node_modules,_deps}/**' \
       -g '*.{cpp,h,hpp,c,cc,cxx}' \
       -e '\b(TODO|FIXME|XXX|HACK|STUB|UNIMPLEMENTED|TBD)\b' \
       "$TARGET_DIR" 2>/dev/null || true
}

# Count TODOs by directory
count_by_directory() {
    find_todos | cut -d: -f1 | sed 's|\(.*\)/.*|\1|' | sort | uniq -c | sort -nr
}

# Generate markdown report
generate_markdown_report() {
    local criticals=$(find_criticals | wc -l)
    local todos=$(find_todos | wc -l)
    local files_with_todos=$(find_todos | cut -d: -f1 | sort -u | wc -l)
    
    cat << EOF
# Technical Debt Report

**Generated**: $(date)
**Target Directory**: \`$TARGET_DIR\`

## Summary

| Metric | Count |
|--------|-------|
| Critical Issues | $criticals |
| TODO/FIXME Items | $todos |
| Files with TODOs | $files_with_todos |

## Critical Issues

EOF

    if [[ $criticals -eq 0 ]]; then
        echo "✅ **No critical issues found** (assert(0), abort, unreachable)"
        echo ""
    else
        echo "⚠️ **Found $criticals critical issues:**"
        echo ""
        echo '```'
        find_criticals
        echo '```'
        echo ""
    fi

    cat << EOF
## TODO Distribution by Component

| Component | Count |
|-----------|-------|
EOF

    count_by_directory | head -20 | while read count dir; do
        component=$(basename "$dir" | sed 's/src\///g')
        echo "| $component | $count |"
    done

    echo ""
    echo "## Top TODO Files"
    echo ""
    
    find_todos | cut -d: -f1 | sort | uniq -c | sort -nr | head -10 | while read count file; do
        echo "- \`$file\`: $count items"
    done

    echo ""
    echo "## Recommendations"
    echo ""
    echo "1. **Address Critical Issues First**: Fix any assert(0)/abort patterns"
    echo "2. **Focus on Core Components**: Prioritize RPC, mining, consensus TODOs"  
    echo "3. **Batch by Component**: Fix all TODOs in one component before moving to next"
    echo "4. **Add TODO Tags**: Use format \`TODO[component][priority]: description\`"
    echo ""
    echo "---"
    echo "*Report generated by sweep_fakery.sh*"
}

# Generate text report
generate_text_report() {
    local criticals=$(find_criticals | wc -l)
    local todos=$(find_todos | wc -l)
    
    echo -e "${BLUE}=== DineroCoin Technical Debt Analysis ===${NC}"
    echo -e "Target: $TARGET_DIR"
    echo -e "Generated: $(date)"
    echo ""
    
    echo -e "${RED}Critical Issues: $criticals${NC}"
    if [[ $criticals -gt 0 ]]; then
        echo -e "${RED}Found critical patterns:${NC}"
        find_criticals | head -10
        echo ""
    else
        echo -e "${GREEN}✅ No critical issues found${NC}"
        echo ""
    fi
    
    echo -e "${YELLOW}TODO/FIXME Items: $todos${NC}"
    echo -e "${BLUE}Top components:${NC}"
    count_by_directory | head -10
    echo ""
    
    echo -e "${BLUE}Recommendation:${NC}"
    if [[ $criticals -gt 0 ]]; then
        echo -e "${RED}1. Fix critical issues immediately${NC}"
    fi
    echo -e "2. Focus on RPC and mining TODOs first"
    echo -e "3. Batch fixes by component for efficiency"
}

# Main execution
main() {
    local criticals=$(find_criticals | wc -l)
    local todos=$(find_todos | wc -l)
    
    if [[ "$FORMAT" == "md" ]]; then
        generate_markdown_report
    else
        generate_text_report
    fi
    
    # Exit based on fail-on setting
    case "$FAIL_ON" in
        "critical")
            if [[ $criticals -gt 0 ]]; then
                echo "❌ FAIL: Found $criticals critical issues" >&2
                exit 1
            fi
            ;;
        "any")
            if [[ $todos -gt 0 ]]; then
                echo "❌ FAIL: Found $todos TODO items" >&2
                exit 1
            fi
            ;;
        "none")
            exit 0
            ;;
    esac
    
    exit 0
}

main "$@"