// AUTO-GENERATED by contrib/seeds/generate-seeds.py from
// contrib/seeds/seeds_main.txt. Do not edit by hand — re-run the
// generator and commit both files together. CI's --check mode
// will fail the build if this header drifts from the input.
//
// Source of truth: contrib/seeds/seeds_main.txt
// Generator:       contrib/seeds/generate-seeds.py
//
// These addresses are compiled into every dinerod / dinero-qt
// binary as the last-resort fallback peer list. When a fresh
// node boots with no peers.dat and no DNS-seed connectivity,
// this is the entire set of peers it can reach without manual
// -addnode configuration.

#pragma once

#include <string>
#include <vector>

namespace dinero::consensus {

// Mainnet fixed seed list (Phase D, v8 peer-discovery).
// One entry per pre-release-curated reachable node.
inline const std::vector<std::string> kFixedSeedsMainnet = {
    "172.93.160.131:20999",   // California (us-west, LA)
    "173.249.195.59:20999",   // Virginia (us-east, VA)
    "96.9.226.98:20999",      // Canada (ca-east)
    "173.249.200.59:20999",   // San Jose (us-west, SJ; replaced retired MO)
};

} // namespace dinero::consensus
