// CUDA backend for IComputeBackend (daemon's GPU mining interface).
//
// Build-gated: only the substantive implementation compiles when
// -DENABLE_GPU_MINING=ON and the CUDA toolkit is found. The kernel source is
// generated at configure time from miner/shaders/sha256d.cu via
// cmake/sha256d_cuda_src.cpp.in and NVRTC-compiled at runtime against the
// running device's exact compute capability. No nvcc, no
// enable_language(CUDA) — this sidesteps the CUDA 12.2 + MSVC 14.44 toolchain
// mismatch (NATIVE-MSVC-PORT-BUGS.md Bug #4).
//
// Single source of truth for the kernel: miner/shaders/sha256d.cu — the same
// file solo-miner's IGpuBackend CUDA backend uses. The kernel is multi-winner
// (returns up to 64 winning nonces per dispatch). IComputeBackend's mine()
// contract is single-winner, so we take the first winner and discard the rest.
//
// Bypasses the prior implementation's two limitations:
//   1. Pre-compiled kernel loaded via nvcc-built launch_sha256d_mine wrapper —
//      hits Bug #4 on MSVC native.
//   2. Phase-11-deferred stub status — the prior file had a top comment
//      "GPU mining deferred to Phase 11+ (after Stratum completion)". That
//      deferral is closed by this port.

#include "mining/gpu/cuda_backend.h"

#ifdef ENABLE_CUDA

#include <cuda.h>
#include <nvrtc.h>

#include <algorithm>
#include <chrono>
#include <cstdint>
#include <cstring>
#include <iostream>
#include <string>
#include <vector>

namespace dinero::gpu {

// Embedded kernel source — generated by CMake configure_file at build time
// from miner/shaders/sha256d.cu via cmake/sha256d_cuda_src.cpp.in.
extern const char* SHA256D_CUDA_SRC;

namespace {

constexpr unsigned int THREADS_PER_BLOCK   = 256u;
constexpr uint32_t     GPU_RESULT_CAPACITY = 64u;
constexpr const char*  KERNEL_NAME         = "sha256d_mine";

bool checkCu(CUresult code, const char* what) {
    if (code == CUDA_SUCCESS) return true;
    const char* name = nullptr;
    const char* desc = nullptr;
    cuGetErrorName(code, &name);
    cuGetErrorString(code, &desc);
    std::cerr << "[CUDA] " << what << " failed: "
              << (name ? name : "?") << " -- "
              << (desc ? desc : "(no description)") << std::endl;
    return false;
}

bool checkNvrtc(nvrtcResult code, const char* what) {
    if (code == NVRTC_SUCCESS) return true;
    std::cerr << "[CUDA] " << what << " failed: "
              << nvrtcGetErrorString(code) << std::endl;
    return false;
}

} // namespace

CUDABackend::CUDABackend() = default;

CUDABackend::~CUDABackend() {
    stop();
}

std::vector<GPUDevice> CUDABackend::enumerateDevices() {
    std::vector<GPUDevice> devices;
    if (cuInit(0) != CUDA_SUCCESS) {
        // Treat as "no devices" rather than an error — matches Runtime API
        // semantics where cudaGetDeviceCount returns 0 on a system with no
        // CUDA driver installed.
        return devices;
    }

    int device_count = 0;
    if (!checkCu(cuDeviceGetCount(&device_count), "cuDeviceGetCount")) return devices;

    for (int d = 0; d < device_count; ++d) {
        CUdevice dev;
        if (!checkCu(cuDeviceGet(&dev, d), "cuDeviceGet")) continue;

        char name_buf[256] = {0};
        cuDeviceGetName(name_buf, sizeof(name_buf) - 1, dev);

        size_t total_mem = 0;
        cuDeviceTotalMem(&total_mem, dev);

        int sms       = 0;
        int clock_khz = 0;
        int cc_major  = 0;
        int cc_minor  = 0;
        cuDeviceGetAttribute(&sms,       CU_DEVICE_ATTRIBUTE_MULTIPROCESSOR_COUNT,    dev);
        cuDeviceGetAttribute(&clock_khz, CU_DEVICE_ATTRIBUTE_CLOCK_RATE,              dev);
        cuDeviceGetAttribute(&cc_major,  CU_DEVICE_ATTRIBUTE_COMPUTE_CAPABILITY_MAJOR, dev);
        cuDeviceGetAttribute(&cc_minor,  CU_DEVICE_ATTRIBUTE_COMPUTE_CAPABILITY_MINOR, dev);

        GPUDevice gd;
        gd.backend          = BackendType::CUDA;
        gd.device_id        = static_cast<uint32_t>(d);
        gd.name             = name_buf;
        gd.vendor           = "NVIDIA Corporation";
        gd.global_memory_mb = static_cast<size_t>(total_mem / (1024ull * 1024ull));
        gd.compute_units    = static_cast<uint32_t>(sms);
        gd.max_clock_mhz    = static_cast<uint32_t>(clock_khz / 1000);
        gd.available        = true;
        devices.push_back(gd);

        std::cout << "[CUDA] Found device " << d << ": " << gd.name
                  << " -- " << gd.compute_units << " SMs @ " << gd.max_clock_mhz
                  << " MHz, " << gd.global_memory_mb << " MB, Compute "
                  << cc_major << "." << cc_minor << std::endl;
    }
    return devices;
}

bool CUDABackend::initDevice(uint32_t device_id) {
    if (initialized_) {
        std::cerr << "[CUDA] Device already initialized" << std::endl;
        return false;
    }
    if (!checkCu(cuInit(0), "cuInit")) return false;

    int device_count = 0;
    if (!checkCu(cuDeviceGetCount(&device_count), "cuDeviceGetCount")) return false;
    if (device_id >= static_cast<uint32_t>(device_count)) {
        std::cerr << "[CUDA] Invalid device ID: " << device_id << std::endl;
        return false;
    }

    CUdevice dev;
    if (!checkCu(cuDeviceGet(&dev, static_cast<int>(device_id)), "cuDeviceGet")) return false;
    device_handle_ = static_cast<int>(dev);

    char name_buf[256] = {0};
    cuDeviceGetName(name_buf, sizeof(name_buf) - 1, dev);
    device_name_ = name_buf;

    cuDeviceGetAttribute(&compute_cap_major_,
                         CU_DEVICE_ATTRIBUTE_COMPUTE_CAPABILITY_MAJOR, dev);
    cuDeviceGetAttribute(&compute_cap_minor_,
                         CU_DEVICE_ATTRIBUTE_COMPUTE_CAPABILITY_MINOR, dev);

    CUcontext ctx;
    if (!checkCu(cuCtxCreate(&ctx, 0, dev), "cuCtxCreate")) return false;
    context_ = ctx;

    std::cout << "[CUDA] Initialized device " << device_id
              << " (" << device_name_ << "), compute "
              << compute_cap_major_ << "." << compute_cap_minor_ << std::endl;

    initialized_ = true;
    return true;
}

bool CUDABackend::compileKernel(const std::string& kernel_source) {
    if (!initialized_) {
        std::cerr << "[CUDA] Device not initialized" << std::endl;
        return false;
    }

    // If the caller passed empty, use the configure-time-embedded kernel; a
    // non-empty source is honoured for testing / alternate kernels. Callers
    // in production pass empty (or the loaded contents of the .cu file) and
    // get the canonical embedded kernel either way.
    const char* src = kernel_source.empty() ? SHA256D_CUDA_SRC : kernel_source.c_str();

    nvrtcProgram prog = nullptr;
    if (!checkNvrtc(nvrtcCreateProgram(&prog, src, "sha256d.cu", 0, nullptr, nullptr),
                    "nvrtcCreateProgram"))
        return false;

    std::string arch_flag = "--gpu-architecture=compute_" +
                            std::to_string(compute_cap_major_) +
                            std::to_string(compute_cap_minor_);
    const char* opts[] = { arch_flag.c_str() };
    nvrtcResult compile = nvrtcCompileProgram(prog, 1, opts);
    if (compile != NVRTC_SUCCESS) {
        // Surface NVRTC's compile log — without this the caller just sees
        // NVRTC_ERROR_COMPILATION with no detail. Critical for debugging
        // kernel-source drift between the two consumers.
        size_t log_size = 0;
        nvrtcGetProgramLogSize(prog, &log_size);
        std::vector<char> log(log_size);
        nvrtcGetProgramLog(prog, log.data());
        std::cerr << "[CUDA] nvrtcCompileProgram failed for " << arch_flag << ":\n"
                  << log.data() << std::endl;
        nvrtcDestroyProgram(&prog);
        return false;
    }

    size_t ptx_size = 0;
    if (!checkNvrtc(nvrtcGetPTXSize(prog, &ptx_size), "nvrtcGetPTXSize")) {
        nvrtcDestroyProgram(&prog);
        return false;
    }
    std::vector<char> ptx(ptx_size);
    if (!checkNvrtc(nvrtcGetPTX(prog, ptx.data()), "nvrtcGetPTX")) {
        nvrtcDestroyProgram(&prog);
        return false;
    }
    nvrtcDestroyProgram(&prog);

    CUmodule mod;
    if (!checkCu(cuModuleLoadData(&mod, ptx.data()), "cuModuleLoadData"))
        return false;
    module_ = mod;

    CUfunction fn;
    if (!checkCu(cuModuleGetFunction(&fn, mod, KERNEL_NAME),
                 "cuModuleGetFunction(sha256d_mine)"))
        return false;
    kernel_ = fn;

    // Allocate per-dispatch device buffers (reused across mine() calls).
    CUdeviceptr d_h, d_t, d_rn, d_rc;
    if (!checkCu(cuMemAlloc(&d_h,  128),                                 "cuMemAlloc header"))        return false;
    d_header_ = d_h;
    if (!checkCu(cuMemAlloc(&d_t,  32),                                  "cuMemAlloc target"))        return false;
    d_target_ = d_t;
    if (!checkCu(cuMemAlloc(&d_rn, GPU_RESULT_CAPACITY * sizeof(uint32_t)),
                 "cuMemAlloc result_nonces"))                                                          return false;
    d_result_nonces_ = d_rn;
    if (!checkCu(cuMemAlloc(&d_rc, sizeof(uint32_t)),                    "cuMemAlloc result_count"))  return false;
    d_result_count_ = d_rc;

    std::cout << "[CUDA] Kernel compiled (NVRTC PTX for compute_"
              << compute_cap_major_ << compute_cap_minor_
              << ") and device buffers allocated." << std::endl;
    return true;
}

bool CUDABackend::mine(const WorkPackage& work, MiningResult& result) {
    result.backend = BackendType::CUDA;
    result.device_id = static_cast<uint32_t>(device_handle_);

    if (!initialized_ || !kernel_) {
        std::cerr << "[CUDA] Device or kernel not initialized" << std::endl;
        result.found = false;
        result.hashes_tried = 0;
        return false;
    }

    auto t0 = std::chrono::steady_clock::now();

    // Make our context current — required if the caller has touched another
    // CUDA context between mine() invocations.
    cuCtxSetCurrent(context_);

    uint32_t batch_size = static_cast<uint32_t>(
        std::min<uint64_t>(work.getNonceCount(), 1ull << 31));

    // WorkPackage::header is already 32 × u32 (little-endian on the wire per
    // compute_backend.h doc); WorkPackage::target is 8 × u32 (big-endian
    // words per the same doc). These layouts match what the kernel expects.
    if (!checkCu(cuMemcpyHtoD(d_header_, work.header, 128), "cuMemcpyHtoD header")) {
        result.found = false; result.hashes_tried = 0; return false;
    }
    if (!checkCu(cuMemcpyHtoD(d_target_, work.target, 32), "cuMemcpyHtoD target")) {
        result.found = false; result.hashes_tried = 0; return false;
    }
    uint32_t zero = 0;
    if (!checkCu(cuMemcpyHtoD(d_result_count_, &zero, sizeof(zero)),
                 "cuMemcpyHtoD result_count=0")) {
        result.found = false; result.hashes_tried = 0; return false;
    }

    unsigned int grid       = (batch_size + THREADS_PER_BLOCK - 1) / THREADS_PER_BLOCK;
    uint32_t     capacity   = GPU_RESULT_CAPACITY;
    uint32_t     nonce_start = work.nonce_start;
    CUdeviceptr  d_header   = d_header_;
    CUdeviceptr  d_target   = d_target_;
    CUdeviceptr  d_rnonces  = d_result_nonces_;
    CUdeviceptr  d_rcount   = d_result_count_;

    void* args[] = {
        &d_header,
        &d_target,
        &nonce_start,
        &batch_size,
        &d_rnonces,
        &d_rcount,
        &capacity,
    };

    if (!checkCu(cuLaunchKernel(kernel_,
                                grid, 1, 1,
                                THREADS_PER_BLOCK, 1, 1,
                                0,         // shared mem bytes
                                nullptr,   // default stream
                                args,
                                nullptr),
                 "cuLaunchKernel")) {
        result.found = false; result.hashes_tried = 0; return false;
    }
    if (!checkCu(cuCtxSynchronize(), "cuCtxSynchronize")) {
        result.found = false; result.hashes_tried = 0; return false;
    }

    uint32_t total_count = 0;
    if (!checkCu(cuMemcpyDtoH(&total_count, d_result_count_, sizeof(total_count)),
                 "cuMemcpyDtoH result_count")) {
        result.found = false; result.hashes_tried = 0; return false;
    }

    result.hashes_tried = batch_size;
    result.found        = (total_count > 0);

    if (result.found) {
        // Take the first winner. Kernel is multi-winner (up to
        // GPU_RESULT_CAPACITY) but IComputeBackend's mine() contract is
        // single-winner. Solo-miner uses the multi-winner path via
        // IGpuBackend::dispatch — same kernel, different interface.
        uint32_t first_nonce = 0;
        if (!checkCu(cuMemcpyDtoH(&first_nonce, d_result_nonces_, sizeof(first_nonce)),
                     "cuMemcpyDtoH result_nonces[0]")) {
            result.found = false;
            return false;
        }
        result.nonce = first_nonce;
        std::cout << "[CUDA] Solution found: nonce 0x"
                  << std::hex << result.nonce << std::dec
                  << " (" << total_count << " total winners this dispatch)" << std::endl;
        // result.hash[8] left zero — callers re-validate via consensus path.
    }

    auto t1 = std::chrono::steady_clock::now();
    double ms = std::chrono::duration<double, std::milli>(t1 - t0).count();
    if (ms > 0.0) hashrate_ = (static_cast<double>(batch_size) / ms) * 1000.0;

    return true;
}

void CUDABackend::stop() {
    if (d_result_count_)  { cuMemFree(d_result_count_);  d_result_count_  = 0; }
    if (d_result_nonces_) { cuMemFree(d_result_nonces_); d_result_nonces_ = 0; }
    if (d_target_)        { cuMemFree(d_target_);        d_target_        = 0; }
    if (d_header_)        { cuMemFree(d_header_);        d_header_        = 0; }

    if (module_)  { cuModuleUnload(module_);  module_  = nullptr; }
    if (context_) { cuCtxDestroy(context_);   context_ = nullptr; }

    kernel_        = nullptr;
    device_handle_ = -1;
    initialized_   = false;
    hashrate_      = 0.0;
}

double CUDABackend::getHashrate() const {
    return hashrate_;
}

std::string CUDABackend::getDeviceName() const {
    return device_name_.empty() ? "CUDA (not initialized)" : device_name_;
}

} // namespace dinero::gpu

#else // !ENABLE_CUDA — stub implementation when CUDA is not compiled in

#include <iostream>

namespace dinero::gpu {

CUDABackend::CUDABackend() = default;
CUDABackend::~CUDABackend() = default;

std::vector<GPUDevice> CUDABackend::enumerateDevices() { return {}; }

bool CUDABackend::initDevice(uint32_t) {
    std::cerr << "[CUDA] CUDA support not compiled in "
                 "(rebuild with -DENABLE_GPU_MINING=ON)." << std::endl;
    return false;
}

bool CUDABackend::compileKernel(const std::string&) { return false; }

bool CUDABackend::mine(const WorkPackage&, MiningResult& result) {
    result.found        = false;
    result.hashes_tried = 0;
    return false;
}

void CUDABackend::stop() {}
double CUDABackend::getHashrate() const { return 0.0; }
std::string CUDABackend::getDeviceName() const { return "CUDA (not built)"; }

} // namespace dinero::gpu

#endif // ENABLE_CUDA
