// Copyright (c) 2026 Dinero Labs.
//
// Cross-implementation shielded protocol vectors. The expected bytes are
// generated by scripts/generate_shielded_protocol_vectors.py, a standard-
// library-only implementation which imports and links no Dinero code.

#include <gtest/gtest.h>

#include "consensus/shielded/anchor_history.h"
#include "consensus/shielded/commitment_tree.h"
#include "consensus/shielded/binding_sig.h"
#include "consensus/shielded/nullifier_set.h"
#include "consensus/shielded/range_proof.h"
#include "consensus/shielded/shielded_epoch.h"
#include "consensus/shielded/shielded_serialization.h"
#include "crypto/evp_secp256k1.h"
#include "primitives/transaction.h"
#include "wallet/shielded_derivation.h"
#include "zk/zkvm/hyrax.h"
#include "zk/zkvm/r1cs_spartan.h"
#include "zk/zkvm/scalar.h"
#include "zk/zkvm/transcript.h"

#include <json/json.h>

#include <algorithm>
#include <array>
#include <cstdint>
#include <cstring>
#include <fstream>
#include <sstream>
#include <stdexcept>
#include <string>
#include <vector>

namespace {

namespace sh = dinero::consensus::shielded;
namespace drv = dinero::wallet::shielded;
using dinero::zk::zkvm::Scalar;
using dinero::zk::zkvm::Transcript;

#ifndef SHIELDED_PROTOCOL_VECTOR_FILE
#error "SHIELDED_PROTOCOL_VECTOR_FILE must name the independent JSON fixture"
#endif

std::vector<uint8_t> FromHex(const std::string& text) {
    if (text.size() % 2 != 0) throw std::runtime_error("odd hex length");
    std::vector<uint8_t> out(text.size() / 2);
    auto nibble = [](char c) -> uint8_t {
        if (c >= '0' && c <= '9') return static_cast<uint8_t>(c - '0');
        if (c >= 'a' && c <= 'f') return static_cast<uint8_t>(c - 'a' + 10);
        if (c >= 'A' && c <= 'F') return static_cast<uint8_t>(c - 'A' + 10);
        throw std::runtime_error("non-hex character");
    };
    for (size_t i = 0; i < out.size(); ++i) {
        out[i] = static_cast<uint8_t>((nibble(text[2 * i]) << 4) |
                                      nibble(text[2 * i + 1]));
    }
    return out;
}

template <size_t N>
std::array<uint8_t, N> ArrayFromHex(const std::string& text) {
    const auto bytes = FromHex(text);
    if (bytes.size() != N) throw std::runtime_error("wrong fixed hex length");
    std::array<uint8_t, N> out{};
    std::copy(bytes.begin(), bytes.end(), out.begin());
    return out;
}

std::string Hex(const uint8_t* data, size_t size) {
    static constexpr char alphabet[] = "0123456789abcdef";
    std::string out(size * 2, '0');
    for (size_t i = 0; i < size; ++i) {
        out[2 * i] = alphabet[data[i] >> 4];
        out[2 * i + 1] = alphabet[data[i] & 0x0f];
    }
    return out;
}

template <typename Container>
std::string Hex(const Container& value) {
    return Hex(value.data(), value.size());
}

const Json::Value& Vectors() {
    static const Json::Value root = [] {
        std::ifstream input(SHIELDED_PROTOCOL_VECTOR_FILE);
        if (!input) throw std::runtime_error("cannot open independent shielded vector file");
        Json::CharReaderBuilder builder;
        Json::Value parsed;
        std::string errors;
        if (!Json::parseFromStream(builder, input, &parsed, &errors)) {
            throw std::runtime_error("cannot parse independent shielded vectors: " + errors);
        }
        return parsed;
    }();
    return root;
}

std::array<uint8_t, 64> CanonicalSeed() {
    constexpr char tag[] = "DIN/v7/shielded/derivation/v1";
    std::array<uint8_t, 64> seed{};
    std::memcpy(seed.data(), tag, sizeof(tag) - 1);
    for (size_t i = 0; i < 32; ++i) seed[32 + i] = seed[i] ^ 0xff;
    return seed;
}

TEST(ShieldedExternalVectors, MetadataMakesTheBoundaryExplicit) {
    const auto& root = Vectors();
    EXPECT_EQ(root["format"].asString(), "dinero-shielded-protocol-v1-independent-vectors");
    EXPECT_EQ(root["version"].asUInt(), 1u);
    const auto& excluded = root["scope"]["not_claimed"];
    ASSERT_TRUE(excluded.isArray());
    bool gate_e_is_excluded = false;
    bool outgoing_recovery_is_excluded = false;
    for (const auto& item : excluded) {
        gate_e_is_excluded |= item.asString().find("Gate E") != std::string::npos;
        outgoing_recovery_is_excluded |= item.asString().find("outgoing-view") != std::string::npos;
    }
    EXPECT_TRUE(gate_e_is_excluded);
    EXPECT_TRUE(outgoing_recovery_is_excluded);
}

TEST(ShieldedExternalVectors, PoseidonFinalsMatchIndependentRoundImplementation) {
    sh::Hash zero{};
    sh::Hash one{};
    sh::Hash two{};
    one[31] = 1;
    two[31] = 2;
    EXPECT_EQ(Hex(sh::PoseidonHash2(zero, zero)),
              Vectors()["poseidon"]["zero_zero"]["output"].asString());
    EXPECT_EQ(Hex(sh::PoseidonHash2(one, two)),
              Vectors()["poseidon"]["one_two"]["output"].asString());
    EXPECT_EQ(Vectors()["poseidon"]["round_constants"].size(), 64u);
    EXPECT_EQ(Vectors()["poseidon"]["zero_zero"]["states"].size(), 65u);
    EXPECT_EQ(Vectors()["poseidon"]["one_two"]["states"].size(), 65u);
}

TEST(ShieldedExternalVectors, KeyAndAddressDerivationMatch) {
    const auto seed = CanonicalSeed();
    const auto keys = drv::DeriveShieldedAccount(seed.data(), seed.size(), 0);
    const auto& expected = Vectors()["derivation"];
    EXPECT_EQ(Hex(keys.sk), expected["sk"].asString());
    EXPECT_EQ(Hex(keys.ask), expected["ask"].asString());
    EXPECT_EQ(Hex(keys.nsk), expected["nsk"].asString());
    EXPECT_EQ(Hex(keys.ovk), expected["ovk"].asString());
    EXPECT_EQ(Hex(keys.dk), expected["dk"].asString());
    EXPECT_EQ(Hex(keys.ak), expected["ak"].asString());
    EXPECT_EQ(Hex(keys.nk), expected["nk"].asString());
    EXPECT_EQ(Hex(keys.ivk), expected["ivk"].asString());

    const auto address = drv::DeriveDiversifiedAddress(keys, 0, drv::kHrpMainnet);
    const auto& address_expected = expected["address_j0"];
    EXPECT_EQ(Hex(address.d), address_expected["d"].asString());
    EXPECT_EQ(Hex(drv::HashToPoint(address.d, drv::kDstDiv)), address_expected["p_d"].asString());
    EXPECT_EQ(Hex(address.pk_d), address_expected["pk_d_enc"].asString());
    EXPECT_EQ(Hex(address.pk_d_spend), address_expected["pk_d_spend"].asString());
    EXPECT_EQ(Hex(address.payload), address_expected["payload"].asString());
    EXPECT_EQ(address.address, address_expected["mainnet"].asString());
    EXPECT_EQ(drv::EncodeShieldedAddress(address.payload, drv::kHrpTestnet),
              address_expected["testnet"].asString());
    EXPECT_EQ(drv::EncodeShieldedAddress(address.payload, drv::kHrpRegtest),
              address_expected["regtest"].asString());
}

TEST(ShieldedExternalVectors, NoteEncryptionAndDecryptionMatch) {
    const auto seed = CanonicalSeed();
    const auto keys = drv::DeriveShieldedAccount(seed.data(), seed.size(), 0);
    const auto address = drv::DeriveDiversifiedAddress(keys, 0, drv::kHrpMainnet);
    const auto& expected = Vectors()["note"];

    drv::NotePlaintext note;
    note.d = address.d;
    note.value_una = 100'000'000;
    note.rcm = ArrayFromHex<32>(expected["rcm"].asString());
    note.memo = ArrayFromHex<512>(expected["memo"].asString());
    const auto esk = ArrayFromHex<32>(expected["esk_input"].asString());
    EXPECT_EQ(Hex(note.Serialize()), expected["plaintext"].asString());

    const auto encrypted = drv::EncryptNoteForRecipient(address.d, address.pk_d, note, &esk);
    EXPECT_EQ(Hex(encrypted), expected["encrypted_note"].asString());
    EXPECT_EQ(Hex(encrypted.data(), 32), expected["epk"].asString());

    const auto decrypted = drv::TryDecryptNoteForViewer(keys.ivk, encrypted);
    ASSERT_TRUE(decrypted.has_value());
    EXPECT_EQ(decrypted->d, note.d);
    EXPECT_EQ(decrypted->value_una, note.value_una);
    EXPECT_EQ(decrypted->rcm, note.rcm);
    EXPECT_EQ(decrypted->memo, note.memo);
    EXPECT_EQ(Hex(decrypted->Serialize()), expected["decrypted_plaintext"].asString());
}

TEST(ShieldedExternalVectors, CommitmentsAndNullifiersMatch) {
    const auto& expected = Vectors()["commitment"];
    const auto d = ArrayFromHex<32>(expected["d_packed"].asString());
    const auto pk_note = ArrayFromHex<32>(expected["pk_note"].asString());
    const auto value = ArrayFromHex<32>(expected["value_be32"].asString());
    const auto rcm = ArrayFromHex<32>(Vectors()["note"]["rcm"].asString());
    const auto sk_note = ArrayFromHex<32>(expected["sk_note"].asString());
    EXPECT_EQ(Hex(sh::NoteCommitment(d, pk_note, value, rcm)),
              expected["note_commitment"].asString());
    EXPECT_EQ(Hex(sh::ComputeNullifier(sk_note, 0)), expected["nullifier_leaf_0"].asString());
    EXPECT_EQ(Hex(sh::ComputeNullifier(sk_note, UINT64_MAX)),
              expected["nullifier_leaf_u64max"].asString());
}

void BindTranscript(Transcript& transcript, const std::string& name,
                    const sh::Hash& nullifier, const sh::Hash& anchor,
                    const sh::Hash& commitment, const sh::ValueCommitment& cv) {
    if (name.rfind("spend", 0) == 0) {
        transcript.append_scalar("nf", Scalar(nullifier.data()));
        transcript.append_scalar("an", Scalar(anchor.data()));
    } else {
        transcript.append_scalar("cm", Scalar(commitment.data()));
    }
    if (name.find("v03") != std::string::npos ||
        name.find("v04") != std::string::npos ||
        name.find("v05") != std::string::npos) {
        transcript.append_u64("cv0", cv[0]);
        transcript.append_scalar("cvx", Scalar(cv.data() + 1));
    }
    if (name.find("v05") != std::string::npos) transcript.append_u64("auth", 1);
}

TEST(ShieldedExternalVectors, AllProofVersionTranscriptPreamblesMatch) {
    const auto nullifier = ArrayFromHex<32>(Vectors()["commitment"]["nullifier_leaf_0"].asString());
    const auto commitment = ArrayFromHex<32>(Vectors()["commitment"]["note_commitment"].asString());
    sh::Hash anchor{};
    // The independent oracle uses SHA256("anchor") for transcript-only input.
    const auto anchor_digest = ArrayFromHex<32>("79bfb0e2ba76b9d447606ddbcc494834f05a4c11deb052e74b49ea307a3c5bcd");
    anchor = anchor_digest;
    sh::ValueCommitment cv{};
    cv[0] = 0x08;
    cv.fill(0x66);
    cv[0] = 0x08;

    const std::array<std::pair<const char*, const char*>, 5> cases{{
        {"spend_v01_legacy", "dinero.shielded.spend.v1"},
        {"output_v02_legacy", "dinero.shielded.output.v1"},
        {"spend_v03_cv", "dinero.shielded.spend.v1"},
        {"output_v04_cv", "dinero.shielded.output.v1"},
        {"spend_v05_auth_dormant", "dinero.shielded.spend.v1"},
    }};
    for (const auto& [name, domain] : cases) {
        Transcript transcript(domain);
        BindTranscript(transcript, name, nullifier, anchor, commitment, cv);
        const auto tau = transcript.challenge_scalar("tau",
            dinero::crypto::GetSecp256k1ContextSignVerify());
        EXPECT_EQ(Hex(tau.bytes()), Vectors()["transcripts"][name]["tau"].asString()) << name;
    }
}

TEST(ShieldedExternalVectors, BindingSighashAndSignatureMatch) {
    const auto& expected = Vectors()["binding"];
    dinero::Transaction tx;
    tx.version = dinero::Transaction::TX_VERSION_SHIELDED_V2;
    tx.vin.clear();
    tx.vout = {dinero::TxOutput(dinero::AmountUna::Una(123'456'789), {0x6a, 0x01, 0x42})};
    tx.lockTime = 0x11223344;
    const auto tx_sighash = sh::ComputeShieldedTxSighash(tx);
    EXPECT_EQ(Hex(tx_sighash), expected["tx_sighash"].asString());

    sh::ShieldedSpend spend_a{};
    spend_a.cv = ArrayFromHex<33>(expected["spend_cvs_unsorted"][0].asString());
    sh::ShieldedSpend spend_b{};
    spend_b.cv = ArrayFromHex<33>(expected["spend_cvs_unsorted"][1].asString());
    sh::ShieldedOutput output{};
    output.cv = ArrayFromHex<33>(expected["output_cvs"][0].asString());
    sh::ShieldedBundle bundle{};
    bundle.value_balance = -42;
    bundle.spends = {spend_a, spend_b};
    bundle.outputs = {output};
    const auto sighash = sh::ComputeBindingSighash(bundle, tx_sighash);
    EXPECT_EQ(Hex(sighash), expected["binding_sighash"].asString());

    const auto bsk = ArrayFromHex<32>(expected["bsk"].asString());
    sh::ValueCommitment bvk{};
    ASSERT_EQ(sh::ComputeBvkCommitment(bsk, bvk), sh::BindingSigResult::Ok);
    EXPECT_EQ(Hex(bvk), expected["bvk_commitment"].asString());
    sh::BindingSignature signature{};
    ASSERT_EQ(sh::SignBinding(bsk, sighash, signature), sh::BindingSigResult::Ok);
    EXPECT_EQ(Hex(signature), expected["signature"].asString());
}

sh::ShieldedBundle BundleFixture(const std::string& kind) {
    const auto& root = Vectors();
    const auto commitment = ArrayFromHex<32>(root["commitment"]["note_commitment"].asString());
    const auto nullifier = ArrayFromHex<32>(root["commitment"]["nullifier_leaf_0"].asString());
    sh::ShieldedSpend spend{};
    spend.nullifier = nullifier;
    spend.anchor = ArrayFromHex<32>("f717b640854057a431a60f0189332803976bd3ba7282304a4dbb4706c4fd0813");
    spend.cv = ArrayFromHex<33>("08" + std::string(64, '2'));
    spend.zk_proof = FromHex("03a1b2c3d4");
    sh::ShieldedOutput output{};
    output.commitment = commitment;
    output.cv = ArrayFromHex<33>("09" + std::string(64, '3'));
    output.encrypted_note = FromHex(root["note"]["encrypted_note"].asString());
    output.zk_proof = FromHex("0410203040");

    sh::ShieldedBundle bundle{};
    if (kind == "shield") {
        bundle.value_balance = 100'000'000;
        bundle.outputs = {output};
        bundle.aggregated_range_proof = sh::EncodeAggregatedRangeProof({FromHex("cc")});
    } else if (kind == "transfer") {
        bundle.spends = {spend};
        bundle.outputs = {output};
        bundle.aggregated_range_proof = sh::EncodeAggregatedRangeProof({FromHex("aabb"), FromHex("cc")});
    } else {
        bundle.value_balance = -100'000'000;
        bundle.spends = {spend};
        bundle.aggregated_range_proof = sh::EncodeAggregatedRangeProof({FromHex("aabb")});
    }
    bundle.bvk_commitment = ArrayFromHex<33>("08" + std::string(64, '4'));
    bundle.binding_sig = ArrayFromHex<64>(std::string(128, '5'));
    return bundle;
}

TEST(ShieldedExternalVectors, ShieldTransferUnshieldAndRangeContainersMatch) {
    const auto& expected = Vectors()["operations"];
    for (const std::string kind : {"shield", "transfer", "unshield"}) {
        EXPECT_EQ(Hex(sh::SerializeShieldedBundle(BundleFixture(kind))), expected[kind].asString()) << kind;
    }
    EXPECT_EQ(Hex(sh::EncodeAggregatedRangeProof({FromHex("aabb"), FromHex("cc")})),
              expected["range_container"].asString());

    EXPECT_EQ(Hex(sh::EncodeAggregatedRangeProof({std::vector<uint8_t>(252, 0xa5)})),
              expected["range_compactsize_boundaries"]["proof_252_bytes"].asString());
    EXPECT_EQ(Hex(sh::EncodeAggregatedRangeProof({std::vector<uint8_t>(253, 0x5a)})),
              expected["range_compactsize_boundaries"]["proof_253_bytes"].asString());
}

TEST(ShieldedExternalVectors, FullV6TransactionEnvelopesMatch) {
    const auto& expected = Vectors()["operations"];
    const std::array<std::pair<const char*, uint32_t>, 3> cases{{
        {"shield", 0x01020304},
        {"transfer", 0x11223344},
        {"unshield", 0xa0b0c0d0},
    }};
    for (const auto& [kind, lock_time] : cases) {
        dinero::Transaction tx;
        tx.version = dinero::Transaction::TX_VERSION_SHIELDED_V2;
        tx.witness_version = 0xff;
        dinero::uint256 prev_hash;
        for (size_t i = 0; i < 32; ++i) prev_hash.data[i] = static_cast<uint8_t>(i);
        dinero::TxInput input;
        input.prevout = dinero::TxOutPoint(dinero::TxId(prev_hash), 7);
        input.scriptSig = {0x51, 0x21};
        input.sequence = 0xfffffffd;
        tx.vin = {input};
        tx.vout = {dinero::TxOutput(dinero::AmountUna::Una(12'345), {0x6a, 0x01, 0x7f})};
        tx.lockTime = lock_time;
        tx.shielded_bundle_bytes = FromHex(expected[kind].asString());
        EXPECT_EQ(Hex(tx.Serialize(false)), expected["full_transactions"][kind].asString()) << kind;
        EXPECT_EQ(Hex(tx.Serialize(true)), expected["full_transactions"][kind].asString()) << kind;

        dinero::Transaction decoded;
        const auto wire = FromHex(expected["full_transactions"][kind].asString());
        size_t consumed = 0;
        ASSERT_TRUE(dinero::TransactionSerializer::Deserialize(decoded, wire, consumed)) << kind;
        EXPECT_EQ(consumed, wire.size()) << kind;
        EXPECT_EQ(Hex(decoded.Serialize(false)), expected["full_transactions"][kind].asString()) << kind;
    }
}

TEST(ShieldedExternalVectors, SpartanAndHyraxContainersMatch) {
    auto* ctx = dinero::crypto::GetSecp256k1ContextSignVerify();
    const auto& expected = Vectors()["proof_serialization"];

    const auto commitment_bytes = FromHex(expected["hyrax_commitment_synthetic"].asString());
    dinero::zk::zkvm::HyraxCommitment commitment;
    size_t offset = 0;
    ASSERT_TRUE(dinero::zk::zkvm::HyraxCommitment::deserialize(
        commitment_bytes, offset, commitment, ctx));
    EXPECT_EQ(offset, commitment_bytes.size());
    EXPECT_EQ(Hex(commitment.serialize(ctx)), expected["hyrax_commitment_synthetic"].asString());

    const auto eval_bytes = FromHex(expected["hyrax_eval_synthetic"].asString());
    dinero::zk::zkvm::HyraxEvalProof evaluation;
    offset = 0;
    ASSERT_TRUE(dinero::zk::zkvm::HyraxEvalProof::deserialize(
        eval_bytes, offset, evaluation, ctx));
    EXPECT_EQ(offset, eval_bytes.size());
    EXPECT_EQ(Hex(evaluation.serialize(ctx)), expected["hyrax_eval_synthetic"].asString());

    const auto spartan_bytes = FromHex(expected["spartan_synthetic"].asString());
    dinero::zk::zkvm::SpartanProof spartan;
    ASSERT_TRUE(dinero::zk::zkvm::SpartanProof::deserialize(spartan_bytes, spartan, ctx));
    EXPECT_EQ(Hex(spartan.serialize(ctx)), expected["spartan_synthetic"].asString());
    auto truncated = spartan_bytes;
    truncated.pop_back();
    EXPECT_FALSE(dinero::zk::zkvm::SpartanProof::deserialize(truncated, spartan, ctx));
}

TEST(ShieldedExternalVectors, CanonicalParserAcceptsGoodAndDistinguishesBad) {
    const auto& operations = Vectors()["operations"];
    for (const std::string kind : {"shield", "transfer", "unshield"}) {
        const auto bytes = FromHex(operations[kind].asString());
        sh::ShieldedBundle parsed{};
        EXPECT_EQ(sh::DeserializeShieldedBundle(bytes.data(), bytes.size(), &parsed),
                  sh::BundleDecodeError::Ok) << kind;
    }
    const auto& rejected = operations["canonical_rejections"];
    const auto trailing = FromHex(rejected["trailing_byte"].asString());
    const auto truncated = FromHex(rejected["truncated"].asString());
    const auto nonminimal = FromHex(rejected["nonminimal_spend_count"].asString());
    const auto descending = FromHex(rejected["descending_spends"].asString());
    sh::ShieldedBundle parsed{};
    EXPECT_EQ(sh::DeserializeShieldedBundle(trailing.data(), trailing.size(), &parsed),
              sh::BundleDecodeError::TrailingBytes);
    EXPECT_EQ(sh::DeserializeShieldedBundle(truncated.data(), truncated.size(), &parsed),
              sh::BundleDecodeError::Truncated);
    EXPECT_EQ(sh::DeserializeShieldedBundle(nonminimal.data(), nonminimal.size(), &parsed),
              sh::BundleDecodeError::Truncated);
    EXPECT_EQ(sh::DeserializeShieldedBundle(descending.data(), descending.size(), &parsed),
              sh::BundleDecodeError::OrderViolation);
}

TEST(ShieldedExternalVectors, EpochResetAndReapplyAreByteExact) {
    const auto commitment = ArrayFromHex<32>(Vectors()["commitment"]["note_commitment"].asString());
    const auto second = ArrayFromHex<32>("e7c33750e7fb01926e3d310b0b5990dbdca70559c36b8ef0f11eef46b2d4ba42");
    const auto& expected = Vectors()["epoch_reset"];
    sh::CommitmentTree tree;
    EXPECT_EQ(Hex(tree.Root()), expected["empty_root"].asString());
    tree.Append(commitment);
    EXPECT_EQ(Hex(tree.Root()), expected["root_after_first"].asString());
    tree.Append(second);
    EXPECT_EQ(Hex(tree.Root()), expected["root_after_second"].asString());
    ASSERT_TRUE(tree.Truncate(1));
    EXPECT_EQ(Hex(tree.Root()), expected["root_after_truncate_to_one"].asString());
    ASSERT_TRUE(tree.Truncate(0));
    EXPECT_EQ(Hex(tree.Root()), expected["root_after_reset"].asString());
    tree.Append(commitment);
    tree.Append(second);
    EXPECT_EQ(Hex(tree.Root()), expected["root_after_reapply"].asString());
}

TEST(ShieldedExternalVectors, EpochResetClearsAllPoolState) {
    const auto first = ArrayFromHex<32>(Vectors()["commitment"]["note_commitment"].asString());
    const auto second = ArrayFromHex<32>("e7c33750e7fb01926e3d310b0b5990dbdca70559c36b8ef0f11eef46b2d4ba42");
    const auto nullifier_a = ArrayFromHex<32>(Vectors()["commitment"]["nullifier_leaf_0"].asString());
    const auto nullifier_b = ArrayFromHex<32>(Vectors()["commitment"]["nullifier_leaf_u64max"].asString());
    const auto& expected = Vectors()["epoch_reset"];

    sh::CommitmentTree tree;
    sh::AnchorHistory anchors;
    sh::NullifierSet nullifiers;
    ASSERT_EQ(nullifiers.Open(":memory:"), sh::NullifierSet::OpenResult::Ok);
    tree.Append(first);
    tree.Append(second);
    const auto old_root = tree.Root();
    anchors.RecordRoot(expected["state_before_reset"]["anchor_height"].asUInt(), old_root);
    ASSERT_TRUE(nullifiers.Insert(nullifier_a, 10));
    ASSERT_TRUE(nullifiers.Insert(nullifier_b, 11));
    ASSERT_EQ(tree.Size(), expected["state_before_reset"]["tree_size"].asUInt64());
    ASSERT_EQ(nullifiers.Size(), expected["state_before_reset"]["nullifiers"].size());

    sh::ResetShieldedEpoch(tree, anchors, nullifiers);
    EXPECT_EQ(tree.Size(), expected["state_after_reset"]["tree_size"].asUInt64());
    EXPECT_EQ(Hex(tree.Root()), expected["root_after_reset"].asString());
    EXPECT_EQ(nullifiers.Size(), expected["state_after_reset"]["nullifier_count"].asUInt64());
    EXPECT_EQ(anchors.Contains(old_root), expected["state_after_reset"]["old_anchor_present"].asBool());
}

}  // namespace
