#pragma once

#include "economic_types.h"
#include "economic_trace.h"
#include "mempool_simulator.h"
#include "block_assembler.h"
#include "fee_estimator.h"
#include <memory>
#include <map>
#include <vector>

namespace dinero {
namespace economic {
namespace test {

/**
 * EconomicSimulator - Multi-node economic simulation orchestrator
 *
 * Coordinates economic simulation across multiple nodes:
 * - Each node has independent mempool (MempoolSimulator)
 * - Each node has independent block assembler (BlockAssembler)
 * - Shared fee estimator (or per-node, configurable)
 * - Executes economic actions (submit tx, RBF, mine block, etc.)
 * - Generates complete EconomicTrace for oracle verification
 *
 * Pattern: Observable-facts-only
 * - Actions are inputs (what we command)
 * - Events are outputs (what happened)
 * - State snapshots are periodic checkpoints
 * - Deterministic (same seed + actions → same trace)
 *
 * Integration:
 * - Used by economic property tests (E1-E25)
 * - Produces EconomicTrace for EconomicOracle verification
 * - Extends Ring 5 patterns to economic layer
 *
 * Simplified for Phase 6a:
 * - Single-node focus (multi-node in Phase 6b)
 * - No network simulation (just local mempool)
 * - Focus on mempool + block assembly economics
 */
class EconomicSimulator {
public:
    /**
     * Create economic simulator
     *
     * @param nodes List of node IDs to simulate
     * @param policy Economic policy configuration
     * @param rng_seed Deterministic RNG seed
     */
    EconomicSimulator(
        const std::vector<NodeID>& nodes,
        const EconomicPolicy& policy,
        uint64_t rng_seed
    );

    ~EconomicSimulator();

    // ========================================================================
    // Simulation Control
    // ========================================================================

    /**
     * Reset simulator to initial state
     */
    void reset();

    /**
     * Execute action in simulation
     *
     * @param action Action to execute
     * @return Events generated by this action
     */
    std::vector<EconomicEvent> executeAction(const EconomicAction& action);

    /**
     * Execute sequence of actions
     *
     * @param actions Actions to execute in order
     * @return All events generated
     */
    std::vector<EconomicEvent> executeActions(const std::vector<EconomicAction>& actions);

    /**
     * Advance simulation time
     *
     * @param delta_ms Time to advance (milliseconds)
     */
    void advanceTime(uint64_t delta_ms);

    /**
     * Get current simulation time
     */
    uint64_t getCurrentTime() const {
        return current_time_;
    }

    // ========================================================================
    // Node Queries
    // ========================================================================

    /**
     * Get mempool for specific node
     */
    MempoolSimulator& getMempool(const NodeID& node_id);
    const MempoolSimulator& getMempool(const NodeID& node_id) const;

    /**
     * Get block assembler for specific node
     */
    BlockAssembler& getBlockAssembler(const NodeID& node_id);
    const BlockAssembler& getBlockAssembler(const NodeID& node_id) const;

    /**
     * Get fee estimator (shared or per-node)
     */
    FeeEstimator& getFeeEstimator();
    const FeeEstimator& getFeeEstimator() const;

    /**
     * Get chain height for node
     */
    uint32_t getChainHeight(const NodeID& node_id) const;

    /**
     * Get all nodes
     */
    const std::vector<NodeID>& getNodes() const {
        return nodes_;
    }

    // ========================================================================
    // Trace Extraction
    // ========================================================================

    /**
     * Extract complete economic trace
     *
     * Includes all actions, events, and state snapshots since reset()
     */
    EconomicTrace extractTrace() const;

    /**
     * Get all events since reset
     */
    const std::vector<EconomicEvent>& getAllEvents() const {
        return events_;
    }

    /**
     * Get all actions since reset
     */
    const std::vector<EconomicAction>& getAllActions() const {
        return actions_;
    }

    /**
     * Get all state snapshots
     */
    const std::vector<EconomicState>& getAllSnapshots() const {
        return snapshots_;
    }

    // ========================================================================
    // State Snapshots
    // ========================================================================

    /**
     * Capture state snapshot for all nodes
     *
     * @param timestamp Snapshot time
     */
    void captureSnapshot(uint64_t timestamp);

    /**
     * Capture state snapshot for specific node
     */
    void captureSnapshot(const NodeID& node_id, uint64_t timestamp);

private:
    // Configuration
    std::vector<NodeID> nodes_;
    EconomicPolicy policy_;
    uint64_t rng_seed_;

    // Simulation state
    uint64_t current_time_;
    uint64_t action_sequence_;
    uint64_t event_sequence_;

    // Per-node components
    std::map<NodeID, std::unique_ptr<MempoolSimulator>> mempools_;
    std::map<NodeID, std::unique_ptr<BlockAssembler>> assemblers_;
    std::map<NodeID, uint32_t> chain_heights_;  // Track chain height per node

    // Shared components
    std::shared_ptr<FeeEstimator> fee_estimator_;

    // Trace data
    std::vector<EconomicAction> actions_;
    std::vector<EconomicEvent> events_;
    std::vector<EconomicState> snapshots_;

    // Action handlers
    void handleSubmitTx(const EconomicAction& action);
    void handleReplaceTxRBF(const EconomicAction& action);
    void handleMineBlock(const EconomicAction& action);
    void handleSetMinRelayFee(const EconomicAction& action);
    void handleSetDustThreshold(const EconomicAction& action);
    void handleAdvanceTime(const EconomicAction& action);

    // Event recording
    void recordEvent(EconomicEvent event);
    void recordEvents(const std::vector<EconomicEvent>& events);

    // Helper: Get node or throw
    void validateNode(const NodeID& node_id) const;

    // Helper: Create deterministic transaction entry for testing
    MempoolEntry createMockTx(
        const TxID& tx_id,
        uint64_t fee_una,
        uint32_t size_bytes,
        uint64_t timestamp
    );
};

} // namespace test
} // namespace economic
} // namespace dinero
