#include "economic_simulator.h"
#include <stdexcept>
#include <sstream>

namespace dinero {
namespace economic {
namespace test {

EconomicSimulator::EconomicSimulator(
    const std::vector<NodeID>& nodes,
    const EconomicPolicy& policy,
    uint64_t rng_seed
)
    : nodes_(nodes)
    , policy_(policy)
    , rng_seed_(rng_seed)
    , current_time_(0)
    , action_sequence_(0)
    , event_sequence_(0)
{
    // Create shared fee estimator
    fee_estimator_ = std::make_shared<FeeEstimator>(policy);

    // Create per-node components
    for (const auto& node_id : nodes_) {
        // Create mempool for this node
        mempools_[node_id] = std::make_unique<MempoolSimulator>(
            node_id,
            policy,
            fee_estimator_
        );

        // Create block assembler for this node
        assemblers_[node_id] = std::make_unique<BlockAssembler>(policy);

        // Initialize chain height
        chain_heights_[node_id] = 0;
    }
}

EconomicSimulator::~EconomicSimulator() = default;

void EconomicSimulator::reset() {
    current_time_ = 0;
    action_sequence_ = 0;
    event_sequence_ = 0;

    actions_.clear();
    events_.clear();
    snapshots_.clear();

    // Reset fee estimator
    fee_estimator_->reset();

    // Reset per-node components
    for (const auto& node_id : nodes_) {
        if (mempools_.count(node_id)) {
            mempools_[node_id]->clear();
        }
        if (assemblers_.count(node_id)) {
            assemblers_[node_id]->clearEvents();
        }
        chain_heights_[node_id] = 0;
    }
}

std::vector<EconomicEvent> EconomicSimulator::executeAction(const EconomicAction& action) {
    // Record action
    EconomicAction recorded_action = action;
    recorded_action.sequence_number = action_sequence_++;
    recorded_action.timestamp = current_time_;
    actions_.push_back(recorded_action);

    // Clear event buffer
    size_t events_before = events_.size();

    // Handle action
    switch (action.type) {
        case EconomicActionType::SUBMIT_TX:
            handleSubmitTx(recorded_action);
            break;

        case EconomicActionType::REPLACE_TX_RBF:
            handleReplaceTxRBF(recorded_action);
            break;

        case EconomicActionType::MINE_BLOCK:
            handleMineBlock(recorded_action);
            break;

        case EconomicActionType::SET_MIN_RELAY_FEE:
            handleSetMinRelayFee(recorded_action);
            break;

        case EconomicActionType::SET_DUST_THRESHOLD:
            handleSetDustThreshold(recorded_action);
            break;

        case EconomicActionType::ADVANCE_TIME:
            handleAdvanceTime(recorded_action);
            break;

        default:
            // Unsupported action (log warning event)
            EconomicEvent warning;
            warning.type = EconomicEventType::TX_REJECTED_INVALID;
            warning.timestamp = current_time_;
            warning.sequence_number = event_sequence_++;
            warning.node_id = action.node_id.value_or("simulator");
            warning.success = false;
            warning.error_message = "Unsupported action type";
            recordEvent(warning);
            break;
    }

    // Return events generated by this action
    std::vector<EconomicEvent> generated_events;
    for (size_t i = events_before; i < events_.size(); ++i) {
        generated_events.push_back(events_[i]);
    }

    return generated_events;
}

std::vector<EconomicEvent> EconomicSimulator::executeActions(const std::vector<EconomicAction>& actions) {
    std::vector<EconomicEvent> all_events;
    for (const auto& action : actions) {
        auto events = executeAction(action);
        all_events.insert(all_events.end(), events.begin(), events.end());
    }
    return all_events;
}

void EconomicSimulator::advanceTime(uint64_t delta_ms) {
    current_time_ += delta_ms;
}

MempoolSimulator& EconomicSimulator::getMempool(const NodeID& node_id) {
    validateNode(node_id);
    return *mempools_.at(node_id);
}

const MempoolSimulator& EconomicSimulator::getMempool(const NodeID& node_id) const {
    validateNode(node_id);
    return *mempools_.at(node_id);
}

BlockAssembler& EconomicSimulator::getBlockAssembler(const NodeID& node_id) {
    validateNode(node_id);
    return *assemblers_.at(node_id);
}

const BlockAssembler& EconomicSimulator::getBlockAssembler(const NodeID& node_id) const {
    validateNode(node_id);
    return *assemblers_.at(node_id);
}

FeeEstimator& EconomicSimulator::getFeeEstimator() {
    return *fee_estimator_;
}

const FeeEstimator& EconomicSimulator::getFeeEstimator() const {
    return *fee_estimator_;
}

uint32_t EconomicSimulator::getChainHeight(const NodeID& node_id) const {
    validateNode(node_id);
    return chain_heights_.at(node_id);
}

EconomicTrace EconomicSimulator::extractTrace() const {
    EconomicTrace trace;
    trace.rng_seed = rng_seed_;
    trace.scenario_name = "economic_test";
    trace.nodes = nodes_;
    trace.policy = policy_;

    trace.actions = actions_;
    trace.events = events_;
    trace.snapshots = snapshots_;

    trace.start_time = 0;
    trace.end_time = current_time_;
    trace.completed_successfully = true;

    // Calculate aggregate metrics
    trace.total_txs_submitted = 0;
    trace.total_txs_accepted = 0;
    trace.total_txs_rejected = 0;
    trace.total_txs_confirmed = 0;
    trace.total_fees_collected = 0;
    trace.total_fees_rejected = 0;

    // Count submitted transactions from actions
    for (const auto& action : actions_) {
        if (action.type == EconomicActionType::SUBMIT_TX) {
            trace.total_txs_submitted++;
        }
    }

    // Count outcomes from events
    for (const auto& event : events_) {
        switch (event.type) {
            case EconomicEventType::TX_ACCEPTED_TO_MEMPOOL:
                trace.total_txs_accepted++;
                break;
            case EconomicEventType::TX_REJECTED_LOW_FEE:
            case EconomicEventType::TX_REJECTED_DUST:
            case EconomicEventType::TX_REJECTED_INVALID:
                trace.total_txs_rejected++;
                if (event.fee_una) {
                    trace.total_fees_rejected += *event.fee_una;
                }
                break;
            case EconomicEventType::TX_INCLUDED_IN_BLOCK:
                trace.total_txs_confirmed++;
                if (event.fee_una) {
                    trace.total_fees_collected += *event.fee_una;
                }
                break;
            default:
                break;
        }
    }

    // Compute trace hash
    trace.final_hash = trace.computeHash();

    return trace;
}

void EconomicSimulator::captureSnapshot(uint64_t timestamp) {
    for (const auto& node_id : nodes_) {
        captureSnapshot(node_id, timestamp);
    }
}

void EconomicSimulator::captureSnapshot(const NodeID& node_id, uint64_t timestamp) {
    validateNode(node_id);

    auto& mempool = *mempools_.at(node_id);
    uint32_t chain_height = chain_heights_.at(node_id);

    EconomicState state = mempool.captureState(timestamp, chain_height);
    snapshots_.push_back(state);
}

void EconomicSimulator::handleSubmitTx(const EconomicAction& action) {
    if (!action.node_id) {
        return;  // Invalid action
    }

    validateNode(*action.node_id);

    // Create mock transaction entry
    MempoolEntry entry = createMockTx(
        action.tx_id.value_or("tx_unknown"),
        action.fee_una.value_or(1000),
        action.tx_size_bytes.value_or(250),
        current_time_
    );

    // Override with action values if provided
    if (action.input_value) {
        entry.input_value = *action.input_value;
    }
    if (action.output_value) {
        entry.output_value = *action.output_value;
    }
    if (action.fee_rate) {
        entry.fee_rate = *action.fee_rate;
    }

    // Submit to mempool
    auto& mempool = *mempools_.at(*action.node_id);
    auto event = mempool.submitTransaction(entry, current_time_);

    recordEvent(event);
}

void EconomicSimulator::handleReplaceTxRBF(const EconomicAction& action) {
    if (!action.node_id || !action.tx_id || !action.replaces_tx_id) {
        return;  // Invalid action
    }

    validateNode(*action.node_id);

    // Create new transaction entry
    MempoolEntry new_entry = createMockTx(
        *action.tx_id,
        action.fee_una.value_or(2000),
        action.tx_size_bytes.value_or(250),
        current_time_
    );

    // Mark as RBF
    new_entry.signals_rbf = true;
    new_entry.replaces_tx_id = *action.replaces_tx_id;

    // Replace transaction
    auto& mempool = *mempools_.at(*action.node_id);
    auto event = mempool.replaceTransaction(*action.replaces_tx_id, new_entry, current_time_);

    recordEvent(event);
}

void EconomicSimulator::handleMineBlock(const EconomicAction& action) {
    if (!action.node_id) {
        return;  // Invalid action
    }

    validateNode(*action.node_id);

    auto& mempool = *mempools_.at(*action.node_id);
    auto& assembler = *assemblers_.at(*action.node_id);
    uint32_t chain_height = chain_heights_.at(*action.node_id);

    // Assemble block template
    BlockTemplateState template_state = assembler.assembleTemplate(
        mempool,
        chain_height + 1,
        current_time_
    );

    // Record assembly events
    recordEvents(assembler.getAssemblyEvents());
    assembler.clearEvents();

    // Remove confirmed transactions from mempool
    auto removal_events = mempool.removeTxs(template_state.included_txs, current_time_);
    recordEvents(removal_events);

    // Update fee estimator
    std::vector<MempoolEntry> confirmed_txs;
    for (const auto& tx_id : template_state.included_txs) {
        // Reconstruct mempool entry from event data
        // In a real implementation, we'd track this better
        for (const auto& event : events_) {
            if (event.tx_id && *event.tx_id == tx_id && event.fee_una) {
                MempoolEntry entry;
                entry.tx_id = tx_id;
                entry.fee_una = *event.fee_una;
                entry.tx_size_bytes = event.tx_size_bytes.value_or(250);
                entry.fee_rate = event.fee_rate.value_or(1.0);
                entry.input_value = event.input_value.value_or(100000);
                entry.output_value = event.output_value.value_or(99000);
                entry.entry_time = event.timestamp;
                confirmed_txs.push_back(entry);
                break;
            }
        }
    }

    fee_estimator_->processBlock(chain_height + 1, confirmed_txs, current_time_);

    // Increment chain height
    chain_heights_[*action.node_id]++;

    // Record fee estimate update event
    EconomicEvent fee_update;
    fee_update.type = EconomicEventType::FEE_ESTIMATE_UPDATED;
    fee_update.timestamp = current_time_;
    fee_update.sequence_number = event_sequence_++;
    fee_update.node_id = *action.node_id;
    fee_update.success = true;
    fee_update.block_height = chain_height + 1;
    recordEvent(fee_update);
}

void EconomicSimulator::handleSetMinRelayFee(const EconomicAction& action) {
    if (!action.node_id || !action.min_relay_fee_una) {
        return;
    }

    validateNode(*action.node_id);

    auto& mempool = *mempools_.at(*action.node_id);
    mempool.setMinRelayFee(*action.min_relay_fee_una);

    // Update policy
    policy_.min_relay_fee_una = *action.min_relay_fee_una;
}

void EconomicSimulator::handleSetDustThreshold(const EconomicAction& action) {
    if (!action.node_id || !action.dust_threshold_una) {
        return;
    }

    validateNode(*action.node_id);

    auto& mempool = *mempools_.at(*action.node_id);
    mempool.setDustThreshold(*action.dust_threshold_una);

    // Update policy
    policy_.dust_threshold_una = *action.dust_threshold_una;
}

void EconomicSimulator::handleAdvanceTime(const EconomicAction& action) {
    if (!action.time_delta_ms) {
        return;
    }

    advanceTime(*action.time_delta_ms);
}

void EconomicSimulator::recordEvent(EconomicEvent event) {
    event.sequence_number = event_sequence_++;
    events_.push_back(event);
}

void EconomicSimulator::recordEvents(const std::vector<EconomicEvent>& events) {
    for (auto event : events) {
        recordEvent(event);
    }
}

void EconomicSimulator::validateNode(const NodeID& node_id) const {
    if (mempools_.find(node_id) == mempools_.end()) {
        throw std::runtime_error("Unknown node: " + node_id);
    }
}

MempoolEntry EconomicSimulator::createMockTx(
    const TxID& tx_id,
    uint64_t fee_una,
    uint32_t size_bytes,
    uint64_t timestamp
) {
    MempoolEntry entry;
    entry.tx_id = tx_id;
    entry.fee_una = fee_una;
    entry.tx_size_bytes = size_bytes;
    entry.fee_rate = static_cast<double>(fee_una) / static_cast<double>(size_bytes);
    entry.input_value = fee_una + 100000;  // Mock: inputs = fee + 100k sats
    entry.output_value = 100000;  // Mock: outputs = 100k sats
    entry.entry_time = timestamp;
    entry.signals_rbf = true;  // Allow RBF by default
    return entry;
}

} // namespace test
} // namespace economic
} // namespace dinero
